// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: gateway.proto

package gatewayClient

import (
	"context"

	"im-platform/app/gateway/rpc/gateway"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchPushToConnReq  = gateway.BatchPushToConnReq
	BatchPushToConnResp = gateway.BatchPushToConnResp
	PushToConnReq       = gateway.PushToConnReq
	PushToConnResp      = gateway.PushToConnResp

	Gateway interface {
		PushToConn(ctx context.Context, in *PushToConnReq, opts ...grpc.CallOption) (*PushToConnResp, error)
		// 批量推送:一次 RPC 推多个用户(群聊写扩散用,避免 O(N) 次 Deliver)
		BatchPushToConn(ctx context.Context, in *BatchPushToConnReq, opts ...grpc.CallOption) (*BatchPushToConnResp, error)
	}

	defaultGateway struct {
		cli zrpc.Client
	}
)

func NewGateway(cli zrpc.Client) Gateway {
	return &defaultGateway{
		cli: cli,
	}
}

func (m *defaultGateway) PushToConn(ctx context.Context, in *PushToConnReq, opts ...grpc.CallOption) (*PushToConnResp, error) {
	client := gateway.NewGatewayClient(m.cli.Conn())
	return client.PushToConn(ctx, in, opts...)
}

// 批量推送:一次 RPC 推多个用户(群聊写扩散用,避免 O(N) 次 Deliver)
func (m *defaultGateway) BatchPushToConn(ctx context.Context, in *BatchPushToConnReq, opts ...grpc.CallOption) (*BatchPushToConnResp, error) {
	client := gateway.NewGatewayClient(m.cli.Conn())
	return client.BatchPushToConn(ctx, in, opts...)
}
