// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: gateway.proto

package gatewayclient

import (
	"context"

	"im-platform/app/gateway/rpc/gateway"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PushToConnReq  = gateway.PushToConnReq
	PushToConnResp = gateway.PushToConnResp

	Gateway interface {
		PushToConn(ctx context.Context, in *PushToConnReq, opts ...grpc.CallOption) (*PushToConnResp, error)
	}

	defaultGateway struct {
		cli zrpc.Client
	}
)

func NewGateway(cli zrpc.Client) Gateway {
	return &defaultGateway{
		cli: cli,
	}
}

func (m *defaultGateway) PushToConn(ctx context.Context, in *PushToConnReq, opts ...grpc.CallOption) (*PushToConnResp, error) {
	client := gateway.NewGatewayClient(m.cli.Conn())
	return client.PushToConn(ctx, in, opts...)
}
