// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupsettingsFieldNames          = builder.RawFieldNames(&Groupsettings{}, true)
	groupsettingsRows                = strings.Join(groupsettingsFieldNames, ",")
	groupsettingsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupsettingsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	groupsettingsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(groupsettingsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	groupsettingsModel interface {
		Insert(ctx context.Context, data *Groupsettings) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Groupsettings, error)
		Update(ctx context.Context, data *Groupsettings) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupsettingsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Groupsettings struct {
		Id            int64          `db:"id"`
		UserId        int64          `db:"user_id"`
		GroupId       int64          `db:"group_id"`
		IsMute        bool           `db:"is_mute"`
		IsTop         bool           `db:"is_top"`
		GroupNickname sql.NullString `db:"group_nickname"`
		NoticeReadAt  sql.NullTime   `db:"notice_read_at"`
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
)

func newGroupsettingsModel(conn sqlx.SqlConn) *defaultGroupsettingsModel {
	return &defaultGroupsettingsModel{
		conn:  conn,
		table: `"public"."groupsettings"`,
	}
}

func (m *defaultGroupsettingsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupsettingsModel) FindOne(ctx context.Context, id int64) (*Groupsettings, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", groupsettingsRows, m.table)
	var resp Groupsettings
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsettingsModel) Insert(ctx context.Context, data *Groupsettings) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, groupsettingsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.GroupId, data.IsMute, data.IsTop, data.GroupNickname, data.NoticeReadAt)
	return ret, err
}

func (m *defaultGroupsettingsModel) Update(ctx context.Context, data *Groupsettings) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, groupsettingsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.GroupId, data.IsMute, data.IsTop, data.GroupNickname, data.NoticeReadAt)
	return err
}

func (m *defaultGroupsettingsModel) tableName() string {
	return m.table
}
