// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupmembersFieldNames          = builder.RawFieldNames(&Groupmembers{}, true)
	groupmembersRows                = strings.Join(groupmembersFieldNames, ",")
	groupmembersRowsExpectAutoSet   = strings.Join(stringx.Remove(groupmembersFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	groupmembersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(groupmembersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	groupmembersModel interface {
		Insert(ctx context.Context, data *Groupmembers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Groupmembers, error)
		Update(ctx context.Context, data *Groupmembers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupmembersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Groupmembers struct {
		Id            int64          `db:"id"`
		GroupId       int64          `db:"group_id"`
		UserId        int64          `db:"user_id"`
		Role          int64          `db:"role"`
		GroupNickname sql.NullString `db:"group_nickname"`
		JoinTime      time.Time      `db:"join_time"`
		MuteUntil     sql.NullTime   `db:"mute_until"`
		LastAckSeq    int64          `db:"last_ack_seq"`
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
)

func newGroupmembersModel(conn sqlx.SqlConn) *defaultGroupmembersModel {
	return &defaultGroupmembersModel{
		conn:  conn,
		table: `"public"."groupmembers"`,
	}
}

func (m *defaultGroupmembersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupmembersModel) FindOne(ctx context.Context, id int64) (*Groupmembers, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", groupmembersRows, m.table)
	var resp Groupmembers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupmembersModel) Insert(ctx context.Context, data *Groupmembers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, groupmembersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.GroupId, data.UserId, data.Role, data.GroupNickname, data.JoinTime, data.MuteUntil, data.LastAckSeq)
	return ret, err
}

func (m *defaultGroupmembersModel) Update(ctx context.Context, data *Groupmembers) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, groupmembersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.GroupId, data.UserId, data.Role, data.GroupNickname, data.JoinTime, data.MuteUntil, data.LastAckSeq)
	return err
}

func (m *defaultGroupmembersModel) tableName() string {
	return m.table
}
