// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupsFieldNames          = builder.RawFieldNames(&Groups{}, true)
	groupsRows                = strings.Join(groupsFieldNames, ",")
	groupsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	groupsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(groupsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	groupsModel interface {
		Insert(ctx context.Context, data *Groups) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Groups, error)
		Update(ctx context.Context, data *Groups) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Groups struct {
		Id               int64          `db:"id"`
		Name             string         `db:"name"`
		Avatar           sql.NullString `db:"avatar"`
		OwnerId          int64          `db:"owner_id"`
		Notice           sql.NullString `db:"notice"`
		MemberCount      int64          `db:"member_count"`
		MaxMember        int64          `db:"max_member"`
		MemberVersion    int64          `db:"member_version"`
		GroupType        int64          `db:"group_type"`
		Status           int64          `db:"status"`
		InvitePermission int64          `db:"invite_permission"`
		JoinApproval     int64          `db:"join_approval"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
		DissolvedAt      sql.NullTime   `db:"dissolved_at"`
	}
)

func newGroupsModel(conn sqlx.SqlConn) *defaultGroupsModel {
	return &defaultGroupsModel{
		conn:  conn,
		table: `"public"."groups"`,
	}
}

func (m *defaultGroupsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupsModel) FindOne(ctx context.Context, id int64) (*Groups, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", groupsRows, m.table)
	var resp Groups
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) Insert(ctx context.Context, data *Groups) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)", m.table, groupsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Avatar, data.OwnerId, data.Notice, data.MemberCount, data.MaxMember, data.MemberVersion, data.GroupType, data.Status, data.InvitePermission, data.JoinApproval, data.DissolvedAt)
	return ret, err
}

func (m *defaultGroupsModel) Update(ctx context.Context, data *Groups) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, groupsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Avatar, data.OwnerId, data.Notice, data.MemberCount, data.MaxMember, data.MemberVersion, data.GroupType, data.Status, data.InvitePermission, data.JoinApproval, data.DissolvedAt)
	return err
}

func (m *defaultGroupsModel) tableName() string {
	return m.table
}
