// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupappliesFieldNames          = builder.RawFieldNames(&Groupapplies{}, true)
	groupappliesRows                = strings.Join(groupappliesFieldNames, ",")
	groupappliesRowsExpectAutoSet   = strings.Join(stringx.Remove(groupappliesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	groupappliesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(groupappliesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	groupappliesModel interface {
		Insert(ctx context.Context, data *Groupapplies) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Groupapplies, error)
		FindOneByGroupIdApplicantId(ctx context.Context, groupId int64, applicantId int64) (*Groupapplies, error)
		Update(ctx context.Context, data *Groupapplies) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupappliesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Groupapplies struct {
		Id          int64          `db:"id"`
		GroupId     int64          `db:"group_id"`
		ApplicantId int64          `db:"applicant_id"`
		InviterId   sql.NullInt64  `db:"inviter_id"`
		ApplyType   int64          `db:"apply_type"`
		ApplyReason sql.NullString `db:"apply_reason"`
		Status      int64          `db:"status"`
		HandlerId   sql.NullInt64  `db:"handler_id"`
		CreatedAt   time.Time      `db:"created_at"`
		HandledAt   sql.NullTime   `db:"handled_at"`
	}
)

func newGroupappliesModel(conn sqlx.SqlConn) *defaultGroupappliesModel {
	return &defaultGroupappliesModel{
		conn:  conn,
		table: `"public"."groupapplies"`,
	}
}

func (m *defaultGroupappliesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupappliesModel) FindOne(ctx context.Context, id int64) (*Groupapplies, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", groupappliesRows, m.table)
	var resp Groupapplies
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupappliesModel) FindOneByGroupIdApplicantId(ctx context.Context, groupId int64, applicantId int64) (*Groupapplies, error) {
	var resp Groupapplies
	query := fmt.Sprintf("select %s from %s where group_id = $1 and applicant_id = $2 limit 1", groupappliesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, groupId, applicantId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupappliesModel) Insert(ctx context.Context, data *Groupapplies) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, groupappliesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.GroupId, data.ApplicantId, data.InviterId, data.ApplyType, data.ApplyReason, data.Status, data.HandlerId, data.HandledAt)
	return ret, err
}

func (m *defaultGroupappliesModel) Update(ctx context.Context, newData *Groupapplies) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, groupappliesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.GroupId, newData.ApplicantId, newData.InviterId, newData.ApplyType, newData.ApplyReason, newData.Status, newData.HandlerId, newData.HandledAt)
	return err
}

func (m *defaultGroupappliesModel) tableName() string {
	return m.table
}
