// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: push.proto

package pushclient

import (
	"context"

	"im-platform/app/push/rpc/push"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchDeliverReq  = push.BatchDeliverReq
	BatchDeliverResp = push.BatchDeliverResp
	ClearUnreadReq   = push.ClearUnreadReq
	ClearUnreadResp  = push.ClearUnreadResp
	DeliverReq       = push.DeliverReq
	DeliverResp      = push.DeliverResp
	PushMessage      = push.PushMessage

	Push interface {
		// 单用户投递,语义见 internal/logic/deliverlogic.go(在线推 Gateway;离线/全设备失败转离线信箱+未读计数)
		Deliver(ctx context.Context, in *DeliverReq, opts ...grpc.CallOption) (*DeliverResp, error)
		// 多用户批量投递,语义见 internal/logic/batchDeliverLogic.go(受限并发,顺序契约见 PushMessage.seq_id)
		BatchDeliver(ctx context.Context, in *BatchDeliverReq, opts ...grpc.CallOption) (*BatchDeliverResp, error)
		// 清未读计数,语义见 internal/logic/clearunreadlogic.go
		ClearUnread(ctx context.Context, in *ClearUnreadReq, opts ...grpc.CallOption) (*ClearUnreadResp, error)
	}

	defaultPush struct {
		cli zrpc.Client
	}
)

func NewPush(cli zrpc.Client) Push {
	return &defaultPush{
		cli: cli,
	}
}

// 单用户投递,语义见 internal/logic/deliverlogic.go(在线推 Gateway;离线/全设备失败转离线信箱+未读计数)
func (m *defaultPush) Deliver(ctx context.Context, in *DeliverReq, opts ...grpc.CallOption) (*DeliverResp, error) {
	client := push.NewPushClient(m.cli.Conn())
	return client.Deliver(ctx, in, opts...)
}

// 多用户批量投递,语义见 internal/logic/batchDeliverLogic.go(受限并发,顺序契约见 PushMessage.seq_id)
func (m *defaultPush) BatchDeliver(ctx context.Context, in *BatchDeliverReq, opts ...grpc.CallOption) (*BatchDeliverResp, error) {
	client := push.NewPushClient(m.cli.Conn())
	return client.BatchDeliver(ctx, in, opts...)
}

// 清未读计数,语义见 internal/logic/clearunreadlogic.go
func (m *defaultPush) ClearUnread(ctx context.Context, in *ClearUnreadReq, opts ...grpc.CallOption) (*ClearUnreadResp, error) {
	client := push.NewPushClient(m.cli.Conn())
	return client.ClearUnread(ctx, in, opts...)
}
