// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: push.proto

package server

import (
	"context"

	"im-platform/app/push/rpc/internal/logic"
	"im-platform/app/push/rpc/internal/svc"
	"im-platform/app/push/rpc/push"
)

type PushServer struct {
	svcCtx *svc.ServiceContext
	push.UnimplementedPushServer
}

func NewPushServer(svcCtx *svc.ServiceContext) *PushServer {
	return &PushServer{
		svcCtx: svcCtx,
	}
}

// 单用户投递,语义见 internal/logic/deliverlogic.go(在线推 Gateway;离线/全设备失败转离线信箱+未读计数)
func (s *PushServer) Deliver(ctx context.Context, in *push.DeliverReq) (*push.DeliverResp, error) {
	l := logic.NewDeliverLogic(ctx, s.svcCtx)
	return l.Deliver(ctx, in)
}

// 多用户批量投递,语义见 internal/logic/batchDeliverLogic.go(受限并发,顺序契约见 PushMessage.seq_id)
func (s *PushServer) BatchDeliver(ctx context.Context, in *push.BatchDeliverReq) (*push.BatchDeliverResp, error) {
	l := logic.NewBatchDeliverLogic(ctx, s.svcCtx)
	return l.BatchDeliver(in)
}

// 清未读计数,语义见 internal/logic/clearunreadlogic.go
func (s *PushServer) ClearUnread(ctx context.Context, in *push.ClearUnreadReq) (*push.ClearUnreadResp, error) {
	l := logic.NewClearUnreadLogic(ctx, s.svcCtx)
	return l.ClearUnread(in)
}
