// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: file.proto

package server

import (
	"context"

	"im-platform/app/file/rpc/file"
	"im-platform/app/file/rpc/internal/logic"
	"im-platform/app/file/rpc/internal/svc"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

// 初始化分片上传任务，返回 upload_id 与各分片预签名 URL
func (s *FileServer) CreateUploadTask(ctx context.Context, in *file.CreateUploadTaskReq) (*file.CreateUploadTaskResp, error) {
	l := logic.NewCreateUploadTaskLogic(ctx, s.svcCtx)
	return l.CreateUploadTask(in)
}

// 客户端所有分片上传完成后调用，触发合并、格式校验、安全审核
func (s *FileServer) CompleteUpload(ctx context.Context, in *file.CompleteUploadReq) (*file.CompleteUploadResp, error) {
	l := logic.NewCompleteUploadLogic(ctx, s.svcCtx)
	return l.CompleteUpload(in)
}

// 查询文件元数据（含审核状态、缩略图地址）
func (s *FileServer) GetFileMeta(ctx context.Context, in *file.GetFileMetaReq) (*file.GetFileMetaResp, error) {
	l := logic.NewGetFileMetaLogic(ctx, s.svcCtx)
	return l.GetFileMeta(in)
}

// 重新签发下载预签名 URL（客户端 URL 过期时刷新）
func (s *FileServer) GeneratePresignedUrl(ctx context.Context, in *file.GeneratePresignedUrlReq) (*file.GeneratePresignedUrlResp, error) {
	l := logic.NewGeneratePresignedUrlLogic(ctx, s.svcCtx)
	return l.GeneratePresignedUrl(in)
}

// 删除文件（物理删除 MinIO + 清理元数据）
func (s *FileServer) DeleteFile(ctx context.Context, in *file.DeleteFileReq) (*file.DeleteFileResp, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}
