// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// 手工维护:与 api/api.api 同步;身份类字段(user_id/creator_id/inviter_id 等)一律不进请求体,
// 由鉴权中间件注入 ctx 后在 logic 里取

package types

// ==================== 通用 ====================

type SuccessResp struct {
	Success bool `json:"success"`
}

// ==================== 认证 ====================

type LoginReq struct {
	Phone      string `json:"phone,optional"`
	Email      string `json:"email,optional"`
	Account    string `json:"account,optional"`
	DeviceType int32  `json:"devicetype,optional"`
	DeviceId   string `json:"deviceid,optional"`
	Password   string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Account int64 `json:"account"`
}

type ResetPasswordReq struct {
	Phone       string `json:"phone,optional"`
	Email       string `json:"email,optional"`
	OldPassword string `json:"old_password,optional"`
	NewPassword string `json:"new_password"`
	VerifyCode  string `json:"verify_code,optional"`
}

// ==================== 用户资料/设备 ====================

type ProfileReq struct {
	UserId int64 `json:"user_id,optional"` // 0=查本人
}

type ProfileResp struct {
	UserId    int64  `json:"user_id"`
	Phone     string `json:"phone,optional"`
	Email     string `json:"email,optional"`
	Nickname  string `json:"nickname,optional"`
	Avatar    string `json:"avatar,optional"`
	Signature string `json:"signature,optional"`
	Gender    int32  `json:"gender"`
	Region    string `json:"region,optional"`
	Birthday  int64  `json:"birthday"`
	Status    int32  `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UpdateProfileReq struct {
	Nickname  string `json:"nickname,optional"`
	Avatar    string `json:"avatar,optional"`
	Signature string `json:"signature,optional"`
	Gender    int32  `json:"gender,optional"`
	Region    string `json:"region,optional"`
	Birthday  int64  `json:"birthday,optional"`
}

type Device struct {
	Id           int64  `json:"id"`
	DeviceType   int32  `json:"device_type"`
	DeviceName   string `json:"device_name,optional"`
	DeviceId     string `json:"device_id,optional"`
	Location     string `json:"location,optional"`
	LoginAt      int64  `json:"login_at"`
	LastActiveAt int64  `json:"last_active_at"`
	Status       int32  `json:"status"`
}

type DevicesResp struct {
	Devices []Device `json:"devices"`
}

type KickDeviceReq struct {
	DeviceId int64 `json:"device_id"`
}

// ==================== 好友 ====================

type GetFriendsReq struct {
	FriendGroupId int64  `json:"friend_group_id,optional"`
	Keyword       string `json:"keyword,optional"`
	Page          int32  `json:"page,optional"`
	PageSize      int32  `json:"page_size,optional"`
}

type Friend struct {
	UserId        int64  `json:"user_id"`
	Nickname      string `json:"nickname,optional"`
	Avatar        string `json:"avatar,optional"`
	Remark        string `json:"remark,optional"`
	FriendGroupId int64  `json:"friend_group_id"`
	CreatedAt     int64  `json:"created_at"`
}

type GetFriendsResp struct {
	Total   int32    `json:"total"`
	Friends []Friend `json:"friends"`
}

type GetFriendAppliesReq struct {
	Status   int32 `json:"status,optional"`
	Page     int32 `json:"page,optional"`
	PageSize int32 `json:"page_size,optional"`
}

type FriendApply struct {
	Id                int64  `json:"id"`
	ApplicantId       int64  `json:"applicant_id"`
	ApplicantNickname string `json:"applicant_nickname,optional"`
	ApplicantAvatar   string `json:"applicant_avatar,optional"`
	TargetId          int64  `json:"target_id"`
	ApplyReason       string `json:"apply_reason,optional"`
	Status            int32  `json:"status"`
	CreatedAt         int64  `json:"created_at"`
	HandledAt         int64  `json:"handled_at"`
}

type GetFriendAppliesResp struct {
	Total   int32         `json:"total"`
	Applies []FriendApply `json:"applies"`
}

type AddFriendReq struct {
	TargetUserId int64  `json:"target_user_id"`
	ApplyReason  string `json:"apply_reason,optional"`
}

type AddFriendResp struct {
	ApplyId int64 `json:"apply_id"`
}

type AcceptFriendReq struct {
	ApplyId int64  `json:"apply_id"`
	Remark  string `json:"remark,optional"`
}

type DeleteFriendReq struct {
	FriendUserId int64 `json:"friend_user_id"`
}

type BlockUserReq struct {
	TargetUserId int64 `json:"target_user_id"`
}

type RejectFriendReq struct {
	ApplyId int64 `json:"apply_id"`
}

type HandleApplyReq struct {
	ApplyId int64 `json:"apply_id"`
	Approve bool  `json:"approve"` // true-接受入群 false-拒绝
}

// ==================== 群组 ====================

type CreateGroupReq struct {
	Name             string  `json:"name"`
	Avatar           string  `json:"avatar,optional"`
	InitialMembers   []int64 `json:"initial_members,optional"`
	MaxMember        int32   `json:"max_member,optional,default=500"`
	GroupType        int32   `json:"group_type,optional,default=1"`
	InvitePermission int32   `json:"invite_permission,optional,default=1"`
	JoinApproval     int32   `json:"join_approval,optional,default=1"`
}

type CreateGroupResp struct {
	GroupId       int64 `json:"group_id"`
	MemberVersion int64 `json:"member_version"`
}

type InviteMemberReq struct {
	GroupId int64   `json:"group_id"`
	UserIds []int64 `json:"user_ids"`
}

type InviteMemberResp struct {
	FailedUserIds []int64 `json:"failed_user_ids"`
	MemberVersion int64   `json:"member_version"`
}

type GetGroupInfoReq struct {
	GroupId int64 `json:"group_id"`
}

type GroupInfo struct {
	Id               int64  `json:"id"`
	Name             string `json:"name"`
	Avatar           string `json:"avatar,optional"`
	OwnerId          int64  `json:"owner_id"`
	Notice           string `json:"notice,optional"`
	MemberCount      int32  `json:"member_count"`
	MaxMember        int32  `json:"max_member"`
	MemberVersion    int64  `json:"member_version"`
	GroupType        int32  `json:"group_type"`
	Status           int32  `json:"status"`
	InvitePermission int32  `json:"invite_permission"`
	JoinApproval     int32  `json:"join_approval"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

type GetGroupInfoResp struct {
	Info GroupInfo `json:"info"`
}

type GetMembersReq struct {
	GroupId  int64 `json:"group_id"`
	LastId   int64 `json:"last_id,optional"`   // 游标,首页传 0
	PageSize int32 `json:"page_size,optional"` // 默认 200,最大 200
}

type Member struct {
	UserId        int64  `json:"user_id"`
	Role          int32  `json:"role"` // 1-群主 2-管理员 3-普通成员
	GroupNickname string `json:"group_nickname,optional"`
}

type GetMembersResp struct {
	Members       []Member `json:"members"`
	HasMore       bool     `json:"has_more"`
	MemberVersion int64    `json:"member_version"`
	LastId        int64    `json:"last_id"`
}

type GetUserGroupsResp struct {
	GroupIds []int64 `json:"group_ids"`
}

// ---- 群管理(操作者身份全部取自 token) ----

type QuitGroupReq struct {
	GroupId int64 `json:"group_id"`
}

type KickMemberReq struct {
	GroupId  int64 `json:"group_id"`
	TargetId int64 `json:"target_id"`
}

type MuteMemberReq struct {
	GroupId   int64 `json:"group_id"`
	TargetId  int64 `json:"target_id"`
	MuteUntil int64 `json:"mute_until,optional"` // 毫秒时间戳,0=解除禁言
}

type SetAdminReq struct {
	GroupId  int64 `json:"group_id"`
	TargetId int64 `json:"target_id"`
	IsAdmin  bool  `json:"is_admin"`
}

type TransferOwnerReq struct {
	GroupId    int64 `json:"group_id"`
	NewOwnerId int64 `json:"new_owner_id"`
}

type UpdateGroupInfoReq struct {
	GroupId          int64  `json:"group_id"`
	Name             string `json:"name,optional"` // 空=不修改
	Avatar           string `json:"avatar,optional"`
	Notice           string `json:"notice,optional"`
	InvitePermission int32  `json:"invite_permission,optional"` // 0=不修改
	JoinApproval     int32  `json:"join_approval,optional"`
	MaxMember        int32  `json:"max_member,optional"`
}

type ApplyJoinGroupReq struct {
	GroupId     int64  `json:"group_id"`
	ApplyReason string `json:"apply_reason,optional"`
}

type ApplyJoinGroupResp struct {
	ApplyId int64 `json:"apply_id"`
	Status  int32 `json:"status"` // 1-待审批 2-已加入(免审批群)
}

type GetMemberVersionReq struct {
	GroupId int64 `json:"group_id"`
}

type GetMemberVersionResp struct {
	MemberVersion int64 `json:"member_version"`
	MemberCount   int32 `json:"member_count"`
}

type GroupOpResp struct {
	MemberVersion int64 `json:"member_version"` // 变更后的成员版本号
}

// ==================== 消息 ====================

type RecallMessageReq struct {
	MsgId  int64  `json:"msg_id"`
	ConvId string `json:"conv_id"`
}

// ==================== 文件 ====================

type CreateUploadTaskReq struct {
	FileName    string `json:"file_name"`
	FileSize    int64  `json:"file_size"`
	MimeType    string `json:"mime_type"`
	TotalChunks int32  `json:"total_chunks"`
	ChunkSize   int64  `json:"chunk_size,optional"`
	FileType    int32  `json:"file_type"` // 1-图片 2-语音 3-视频 4-文件
}

type ChunkUpload struct {
	ChunkIndex   int32  `json:"chunk_index"`
	PresignedUrl string `json:"presigned_url"`
}

type CreateUploadTaskResp struct {
	FileId   string        `json:"file_id"`
	UploadId string        `json:"upload_id"`
	Chunks   []ChunkUpload `json:"chunks"`
}

type CompleteUploadReq struct {
	FileId   string   `json:"file_id"`
	UploadId string   `json:"upload_id"`
	Etags    []string `json:"etags"`
}

type CompleteUploadResp struct {
	FileId string `json:"file_id"`
	Url    string `json:"url"`
	Status int32  `json:"status"`
}

type GetFileMetaReq struct {
	FileId string `json:"file_id"`
}

type FileMeta struct {
	FileId     string            `json:"file_id"`
	FileName   string            `json:"file_name"`
	FileSize   int64             `json:"file_size"`
	MimeType   string            `json:"mime_type"`
	FileType   int32             `json:"file_type"`
	UploaderId int64             `json:"uploader_id"`
	UploadTime int64             `json:"upload_time"`
	Status     int32             `json:"status"`
	Thumbnails map[string]string `json:"thumbnails,optional"`
}

type GeneratePresignedUrlReq struct {
	FileId string `json:"file_id"`
	Expiry int32  `json:"expiry,optional"` // 秒,默认 900
}

type GeneratePresignedUrlResp struct {
	FileId       string `json:"file_id"`
	PresignedUrl string `json:"presigned_url"`
	ExpiresAt    int64  `json:"expires_at"`
}

type DeleteFileReq struct {
	FileId string `json:"file_id"`
}
