// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package messageclient

import (
	"context"

	"im-platform/app/message/rpc/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AckMessageReq            = message.AckMessageReq
	AckMessageResp           = message.AckMessageResp
	MessageBody              = message.MessageBody
	MessageContent           = message.MessageContent
	MessageExtra             = message.MessageExtra
	RecallMessageReq         = message.RecallMessageReq
	RecallMessageResp        = message.RecallMessageResp
	ReplyRef                 = message.ReplyRef
	SendMessageReq           = message.SendMessageReq
	SendMessageResp          = message.SendMessageResp
	SyncMessageReq           = message.SyncMessageReq
	SyncMessageReq_ConSeq    = message.SyncMessageReq_ConSeq
	SyncMessageResp          = message.SyncMessageResp
	SyncMessageResp_ConvSync = message.SyncMessageResp_ConvSync

	Message interface {
		SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		AckMessage(ctx context.Context, in *AckMessageReq, opts ...grpc.CallOption) (*AckMessageResp, error)
		SyncMessage(ctx context.Context, in *SyncMessageReq, opts ...grpc.CallOption) (*SyncMessageResp, error)
		RecallMessage(ctx context.Context, in *RecallMessageReq, opts ...grpc.CallOption) (*RecallMessageResp, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

func (m *defaultMessage) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultMessage) AckMessage(ctx context.Context, in *AckMessageReq, opts ...grpc.CallOption) (*AckMessageResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.AckMessage(ctx, in, opts...)
}

func (m *defaultMessage) SyncMessage(ctx context.Context, in *SyncMessageReq, opts ...grpc.CallOption) (*SyncMessageResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.SyncMessage(ctx, in, opts...)
}

func (m *defaultMessage) RecallMessage(ctx context.Context, in *RecallMessageReq, opts ...grpc.CallOption) (*RecallMessageResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.RecallMessage(ctx, in, opts...)
}
