// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: file.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUploadTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`           // 原始文件名（如 "avatar.jpg"）
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`          // 总大小（字节）
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`           // 客户端声明的 MIME 类型（如 image/jpeg）
	TotalChunks   int32                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"` // 分片总数（如 10）
	ChunkSize     int64                  `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`       // 每片大小（如 5MB）
	UploaderId    int64                  `protobuf:"varint,6,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`    // 上传者 user_id
	FileType      int32                  `protobuf:"varint,7,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`          // 1-图片 2-语音 3-视频 4-文件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadTaskReq) Reset() {
	*x = CreateUploadTaskReq{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadTaskReq) ProtoMessage() {}

func (x *CreateUploadTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadTaskReq.ProtoReflect.Descriptor instead.
func (*CreateUploadTaskReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUploadTaskReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateUploadTaskReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CreateUploadTaskReq) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *CreateUploadTaskReq) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *CreateUploadTaskReq) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *CreateUploadTaskReq) GetUploaderId() int64 {
	if x != nil {
		return x.UploaderId
	}
	return 0
}

func (x *CreateUploadTaskReq) GetFileType() int32 {
	if x != nil {
		return x.FileType
	}
	return 0
}

type CreateUploadTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`       // 全局唯一文件 ID（雪花算法，提前分配）
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"` // MinIO 分片上传 ID（Multipart Upload ID）
	Chunks        []*ChunkUploadInfo     `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`                     // 各分片上传信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadTaskResp) Reset() {
	*x = CreateUploadTaskResp{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadTaskResp) ProtoMessage() {}

func (x *CreateUploadTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadTaskResp.ProtoReflect.Descriptor instead.
func (*CreateUploadTaskResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUploadTaskResp) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CreateUploadTaskResp) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CreateUploadTaskResp) GetChunks() []*ChunkUploadInfo {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkUploadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex    int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`      // 分片序号（从 0 开始）
	PresignedUrl  string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"` // 该分片的 PUT 预签名 URL（客户端直接上传 MinIO）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadInfo) Reset() {
	*x = ChunkUploadInfo{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadInfo) ProtoMessage() {}

func (x *ChunkUploadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadInfo.ProtoReflect.Descriptor instead.
func (*ChunkUploadInfo) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkUploadInfo) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkUploadInfo) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

type CompleteUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Etags         []string               `protobuf:"bytes,3,rep,name=etags,proto3" json:"etags,omitempty"` // 各分片上传成功后 MinIO 返回的 ETag，按顺序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadReq) Reset() {
	*x = CompleteUploadReq{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadReq) ProtoMessage() {}

func (x *CompleteUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadReq.ProtoReflect.Descriptor instead.
func (*CompleteUploadReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteUploadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CompleteUploadReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteUploadReq) GetEtags() []string {
	if x != nil {
		return x.Etags
	}
	return nil
}

type CompleteUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`        // 文件访问路径（非预签名，需配合 GeneratePresignedUrl 使用）
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // 1-上传成功待审核 2-审核中 3-审核通过 4-审核拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadResp) Reset() {
	*x = CompleteUploadResp{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadResp) ProtoMessage() {}

func (x *CompleteUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadResp.ProtoReflect.Descriptor instead.
func (*CompleteUploadResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteUploadResp) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CompleteUploadResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CompleteUploadResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetFileMetaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetaReq) Reset() {
	*x = GetFileMetaReq{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetaReq) ProtoMessage() {}

func (x *GetFileMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetaReq.ProtoReflect.Descriptor instead.
func (*GetFileMetaReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileMetaReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileMetaResp struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	FileId     string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName   string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize   int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType   string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileType   int32                  `protobuf:"varint,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // 1-图片 2-语音 3-视频 4-文件
	UploaderId int64                  `protobuf:"varint,6,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	UploadTime int64                  `protobuf:"varint,7,opt,name=upload_time,json=uploadTime,proto3" json:"upload_time,omitempty"` // 毫秒时间戳
	Status     int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                           // 1-正常 2-审核中 3-审核拒绝 4-已删除
	// 缩略图（仅图片/视频有）
	// key: "origin"/"large"/"thumb"
	Thumbnails map[string]string `protobuf:"bytes,9,rep,name=thumbnails,proto3" json:"thumbnails,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 审核结果（status=3 时有效）
	AuditResult   *AuditResult `protobuf:"bytes,10,opt,name=audit_result,json=auditResult,proto3" json:"audit_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetaResp) Reset() {
	*x = GetFileMetaResp{}
	mi := &file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetaResp) ProtoMessage() {}

func (x *GetFileMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetaResp.ProtoReflect.Descriptor instead.
func (*GetFileMetaResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileMetaResp) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetFileMetaResp) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetFileMetaResp) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GetFileMetaResp) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetFileMetaResp) GetFileType() int32 {
	if x != nil {
		return x.FileType
	}
	return 0
}

func (x *GetFileMetaResp) GetUploaderId() int64 {
	if x != nil {
		return x.UploaderId
	}
	return 0
}

func (x *GetFileMetaResp) GetUploadTime() int64 {
	if x != nil {
		return x.UploadTime
	}
	return 0
}

func (x *GetFileMetaResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetFileMetaResp) GetThumbnails() map[string]string {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

func (x *GetFileMetaResp) GetAuditResult() *AuditResult {
	if x != nil {
		return x.AuditResult
	}
	return nil
}

type AuditResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditType     int32                  `protobuf:"varint,1,opt,name=audit_type,json=auditType,proto3" json:"audit_type,omitempty"` // 1-敏感词 2-鉴黄 3-鉴暴 4-垃圾检测
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                        // 2-通过 3-拒绝
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`                         // 审核详情（如命中规则）
	AuditedAt     int64                  `protobuf:"varint,4,opt,name=audited_at,json=auditedAt,proto3" json:"audited_at,omitempty"` // 审核完成时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResult) Reset() {
	*x = AuditResult{}
	mi := &file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResult) ProtoMessage() {}

func (x *AuditResult) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResult.ProtoReflect.Descriptor instead.
func (*AuditResult) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{7}
}

func (x *AuditResult) GetAuditType() int32 {
	if x != nil {
		return x.AuditType
	}
	return 0
}

func (x *AuditResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuditResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AuditResult) GetAuditedAt() int64 {
	if x != nil {
		return x.AuditedAt
	}
	return 0
}

type GeneratePresignedUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Expiry        int32                  `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"` // 过期时间（秒），默认 900（15分钟）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePresignedUrlReq) Reset() {
	*x = GeneratePresignedUrlReq{}
	mi := &file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePresignedUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePresignedUrlReq) ProtoMessage() {}

func (x *GeneratePresignedUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePresignedUrlReq.ProtoReflect.Descriptor instead.
func (*GeneratePresignedUrlReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{8}
}

func (x *GeneratePresignedUrlReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GeneratePresignedUrlReq) GetExpiry() int32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type GeneratePresignedUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"` // 带签名的临时访问 URL
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`         // 过期时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePresignedUrlResp) Reset() {
	*x = GeneratePresignedUrlResp{}
	mi := &file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePresignedUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePresignedUrlResp) ProtoMessage() {}

func (x *GeneratePresignedUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePresignedUrlResp.ProtoReflect.Descriptor instead.
func (*GeneratePresignedUrlResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{9}
}

func (x *GeneratePresignedUrlResp) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GeneratePresignedUrlResp) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *GeneratePresignedUrlResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type DeleteFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者（用于权限校验）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileReq) Reset() {
	*x = DeleteFileReq{}
	mi := &file_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReq) ProtoMessage() {}

func (x *DeleteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReq.ProtoReflect.Descriptor instead.
func (*DeleteFileReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFileReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DeleteFileReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type DeleteFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResp) Reset() {
	*x = DeleteFileResp{}
	mi := &file_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResp) ProtoMessage() {}

func (x *DeleteFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResp.ProtoReflect.Descriptor instead.
func (*DeleteFileResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{11}
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x04file\"\xec\x01\n" +
	"\x13CreateUploadTaskReq\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x03R\tchunkSize\x12\x1f\n" +
	"\vuploader_id\x18\x06 \x01(\x03R\n" +
	"uploaderId\x12\x1b\n" +
	"\tfile_type\x18\a \x01(\x05R\bfileType\"{\n" +
	"\x14CreateUploadTaskResp\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12-\n" +
	"\x06chunks\x18\x03 \x03(\v2\x15.file.ChunkUploadInfoR\x06chunks\"W\n" +
	"\x0fChunkUploadInfo\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\"_\n" +
	"\x11CompleteUploadReq\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\x14\n" +
	"\x05etags\x18\x03 \x03(\tR\x05etags\"W\n" +
	"\x12CompleteUploadResp\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\")\n" +
	"\x0eGetFileMetaReq\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\xb4\x03\n" +
	"\x0fGetFileMetaResp\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\x05R\bfileType\x12\x1f\n" +
	"\vuploader_id\x18\x06 \x01(\x03R\n" +
	"uploaderId\x12\x1f\n" +
	"\vupload_time\x18\a \x01(\x03R\n" +
	"uploadTime\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12E\n" +
	"\n" +
	"thumbnails\x18\t \x03(\v2%.file.GetFileMetaResp.ThumbnailsEntryR\n" +
	"thumbnails\x124\n" +
	"\faudit_result\x18\n" +
	" \x01(\v2\x11.file.AuditResultR\vauditResult\x1a=\n" +
	"\x0fThumbnailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\vAuditResult\x12\x1d\n" +
	"\n" +
	"audit_type\x18\x01 \x01(\x05R\tauditType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"audited_at\x18\x04 \x01(\x03R\tauditedAt\"J\n" +
	"\x17GeneratePresignedUrlReq\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\x05R\x06expiry\"w\n" +
	"\x18GeneratePresignedUrlResp\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"I\n" +
	"\rDeleteFileReq\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\"\x10\n" +
	"\x0eDeleteFileResp2\xe2\x02\n" +
	"\x04File\x12I\n" +
	"\x10CreateUploadTask\x12\x19.file.CreateUploadTaskReq\x1a\x1a.file.CreateUploadTaskResp\x12C\n" +
	"\x0eCompleteUpload\x12\x17.file.CompleteUploadReq\x1a\x18.file.CompleteUploadResp\x12:\n" +
	"\vGetFileMeta\x12\x14.file.GetFileMetaReq\x1a\x15.file.GetFileMetaResp\x12U\n" +
	"\x14GeneratePresignedUrl\x12\x1d.file.GeneratePresignedUrlReq\x1a\x1e.file.GeneratePresignedUrlResp\x127\n" +
	"\n" +
	"DeleteFile\x12\x13.file.DeleteFileReq\x1a\x14.file.DeleteFileRespB\bZ\x06./fileb\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_file_proto_goTypes = []any{
	(*CreateUploadTaskReq)(nil),      // 0: file.CreateUploadTaskReq
	(*CreateUploadTaskResp)(nil),     // 1: file.CreateUploadTaskResp
	(*ChunkUploadInfo)(nil),          // 2: file.ChunkUploadInfo
	(*CompleteUploadReq)(nil),        // 3: file.CompleteUploadReq
	(*CompleteUploadResp)(nil),       // 4: file.CompleteUploadResp
	(*GetFileMetaReq)(nil),           // 5: file.GetFileMetaReq
	(*GetFileMetaResp)(nil),          // 6: file.GetFileMetaResp
	(*AuditResult)(nil),              // 7: file.AuditResult
	(*GeneratePresignedUrlReq)(nil),  // 8: file.GeneratePresignedUrlReq
	(*GeneratePresignedUrlResp)(nil), // 9: file.GeneratePresignedUrlResp
	(*DeleteFileReq)(nil),            // 10: file.DeleteFileReq
	(*DeleteFileResp)(nil),           // 11: file.DeleteFileResp
	nil,                              // 12: file.GetFileMetaResp.ThumbnailsEntry
}
var file_file_proto_depIdxs = []int32{
	2,  // 0: file.CreateUploadTaskResp.chunks:type_name -> file.ChunkUploadInfo
	12, // 1: file.GetFileMetaResp.thumbnails:type_name -> file.GetFileMetaResp.ThumbnailsEntry
	7,  // 2: file.GetFileMetaResp.audit_result:type_name -> file.AuditResult
	0,  // 3: file.File.CreateUploadTask:input_type -> file.CreateUploadTaskReq
	3,  // 4: file.File.CompleteUpload:input_type -> file.CompleteUploadReq
	5,  // 5: file.File.GetFileMeta:input_type -> file.GetFileMetaReq
	8,  // 6: file.File.GeneratePresignedUrl:input_type -> file.GeneratePresignedUrlReq
	10, // 7: file.File.DeleteFile:input_type -> file.DeleteFileReq
	1,  // 8: file.File.CreateUploadTask:output_type -> file.CreateUploadTaskResp
	4,  // 9: file.File.CompleteUpload:output_type -> file.CompleteUploadResp
	6,  // 10: file.File.GetFileMeta:output_type -> file.GetFileMetaResp
	9,  // 11: file.File.GeneratePresignedUrl:output_type -> file.GeneratePresignedUrlResp
	11, // 12: file.File.DeleteFile:output_type -> file.DeleteFileResp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
