// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: push.proto

package push

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Push_Deliver_FullMethodName      = "/push.Push/Deliver"
	Push_BatchDeliver_FullMethodName = "/push.Push/BatchDeliver"
	Push_ClearUnread_FullMethodName  = "/push.Push/ClearUnread"
)

// PushClient is the client API for Push service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushClient interface {
	// 单用户投递,语义见 internal/logic/deliverlogic.go(在线推 Gateway;离线/全设备失败转离线信箱+未读计数)
	Deliver(ctx context.Context, in *DeliverReq, opts ...grpc.CallOption) (*DeliverResp, error)
	// 多用户批量投递,语义见 internal/logic/batchDeliverLogic.go(受限并发,顺序契约见 PushMessage.seq_id)
	BatchDeliver(ctx context.Context, in *BatchDeliverReq, opts ...grpc.CallOption) (*BatchDeliverResp, error)
	// 清未读计数,语义见 internal/logic/clearunreadlogic.go
	ClearUnread(ctx context.Context, in *ClearUnreadReq, opts ...grpc.CallOption) (*ClearUnreadResp, error)
}

type pushClient struct {
	cc grpc.ClientConnInterface
}

func NewPushClient(cc grpc.ClientConnInterface) PushClient {
	return &pushClient{cc}
}

func (c *pushClient) Deliver(ctx context.Context, in *DeliverReq, opts ...grpc.CallOption) (*DeliverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResp)
	err := c.cc.Invoke(ctx, Push_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) BatchDeliver(ctx context.Context, in *BatchDeliverReq, opts ...grpc.CallOption) (*BatchDeliverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeliverResp)
	err := c.cc.Invoke(ctx, Push_BatchDeliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) ClearUnread(ctx context.Context, in *ClearUnreadReq, opts ...grpc.CallOption) (*ClearUnreadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearUnreadResp)
	err := c.cc.Invoke(ctx, Push_ClearUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServer is the server API for Push service.
// All implementations must embed UnimplementedPushServer
// for forward compatibility.
type PushServer interface {
	// 单用户投递,语义见 internal/logic/deliverlogic.go(在线推 Gateway;离线/全设备失败转离线信箱+未读计数)
	Deliver(context.Context, *DeliverReq) (*DeliverResp, error)
	// 多用户批量投递,语义见 internal/logic/batchDeliverLogic.go(受限并发,顺序契约见 PushMessage.seq_id)
	BatchDeliver(context.Context, *BatchDeliverReq) (*BatchDeliverResp, error)
	// 清未读计数,语义见 internal/logic/clearunreadlogic.go
	ClearUnread(context.Context, *ClearUnreadReq) (*ClearUnreadResp, error)
	mustEmbedUnimplementedPushServer()
}

// UnimplementedPushServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServer struct{}

func (UnimplementedPushServer) Deliver(context.Context, *DeliverReq) (*DeliverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedPushServer) BatchDeliver(context.Context, *BatchDeliverReq) (*BatchDeliverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDeliver not implemented")
}
func (UnimplementedPushServer) ClearUnread(context.Context, *ClearUnreadReq) (*ClearUnreadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearUnread not implemented")
}
func (UnimplementedPushServer) mustEmbedUnimplementedPushServer() {}
func (UnimplementedPushServer) testEmbeddedByValue()              {}

// UnsafePushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServer will
// result in compilation errors.
type UnsafePushServer interface {
	mustEmbedUnimplementedPushServer()
}

func RegisterPushServer(s grpc.ServiceRegistrar, srv PushServer) {
	// If the following call panics, it indicates UnimplementedPushServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Push_ServiceDesc, srv)
}

func _Push_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).Deliver(ctx, req.(*DeliverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_BatchDeliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeliverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).BatchDeliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_BatchDeliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).BatchDeliver(ctx, req.(*BatchDeliverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_ClearUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearUnreadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).ClearUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_ClearUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).ClearUnread(ctx, req.(*ClearUnreadReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Push_ServiceDesc is the grpc.ServiceDesc for Push service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Push_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "push.Push",
	HandlerType: (*PushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deliver",
			Handler:    _Push_Deliver_Handler,
		},
		{
			MethodName: "BatchDeliver",
			Handler:    _Push_BatchDeliver_Handler,
		},
		{
			MethodName: "ClearUnread",
			Handler:    _Push_ClearUnread_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push.proto",
}
