// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: push.proto

package push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 推送方式
type PushType int32

const (
	PushType_PushTypeUnspecified PushType = 0
	PushType_PushTypeFull        PushType = 1 // 完整消息推送：单聊、群聊写扩散、大群 @ 提及强推
	PushType_PushTypeNotify      PushType = 2 // 轻量通知：大群读扩散，仅含群 ID + 新 Seq，客户端收到后主动 SyncMessages 拉取
)

// Enum value maps for PushType.
var (
	PushType_name = map[int32]string{
		0: "PushTypeUnspecified",
		1: "PushTypeFull",
		2: "PushTypeNotify",
	}
	PushType_value = map[string]int32{
		"PushTypeUnspecified": 0,
		"PushTypeFull":        1,
		"PushTypeNotify":      2,
	}
)

func (x PushType) Enum() *PushType {
	p := new(PushType)
	*p = x
	return p
}

func (x PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_push_proto_enumTypes[0].Descriptor()
}

func (PushType) Type() protoreflect.EnumType {
	return &file_push_proto_enumTypes[0]
}

func (x PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushType.Descriptor instead.
func (PushType) EnumDescriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0}
}

// 跨服务传递的消息体（精简版，对应 common/types 的 PushPayload）
type PushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`          // 消息全局 ID（雪花算法）
	ConvId        string                 `protobuf:"bytes,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`        // 会话 ID（单聊 min_uid:max_uid / 群聊 group_{group_id}）
	SeqId         int64                  `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`          // 会话内单调递增序列号
	SenderId      int64                  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // 发送者 ID
	MsgType       int64                  `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`    // 1-文本 2-图片 3-语音 4-视频 5-文件 6-位置 7-系统
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                    // 消息内容（JSON 序列化）
	SendTime      int64                  `protobuf:"varint,7,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"` // Unix 毫秒时间戳
	ConvType      bool                   `protobuf:"varint,8,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"` // 会话类型：0-单聊 1-群聊
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessage) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PushMessage) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *PushMessage) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *PushMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *PushMessage) GetMsgType() int64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *PushMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushMessage) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *PushMessage) GetConvType() bool {
	if x != nil {
		return x.ConvType
	}
	return false
}

// 投递指令：Message 服务在单聊/群聊管道中调用
type DeliverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          // 目标用户 ID（单聊接收方 / 群聊成员）
	PushType      PushType               `protobuf:"varint,2,opt,name=push_type,json=pushType,proto3,enum=push.PushType" json:"push_type,omitempty"` // 推送方式
	Message       *PushMessage           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                       // 消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverReq) Reset() {
	*x = DeliverReq{}
	mi := &file_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverReq) ProtoMessage() {}

func (x *DeliverReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverReq.ProtoReflect.Descriptor instead.
func (*DeliverReq) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeliverReq) GetPushType() PushType {
	if x != nil {
		return x.PushType
	}
	return PushType_PushTypeUnspecified
}

func (x *DeliverReq) GetMessage() *PushMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeliverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResp) Reset() {
	*x = DeliverResp{}
	mi := &file_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResp) ProtoMessage() {}

func (x *DeliverResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResp.ProtoReflect.Descriptor instead.
func (*DeliverResp) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 清除未读数：客户端打开会话阅读后调用
type ClearUnreadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID
	ConvId        string                 `protobuf:"bytes,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`  // 会话 ID
	SeqId         int64                  `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`    // 已读到的最大 Seq（用于记录已读锚点）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUnreadReq) Reset() {
	*x = ClearUnreadReq{}
	mi := &file_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUnreadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUnreadReq) ProtoMessage() {}

func (x *ClearUnreadReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUnreadReq.ProtoReflect.Descriptor instead.
func (*ClearUnreadReq) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{3}
}

func (x *ClearUnreadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClearUnreadReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *ClearUnreadReq) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type ClearUnreadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUnreadResp) Reset() {
	*x = ClearUnreadResp{}
	mi := &file_push_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUnreadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUnreadResp) ProtoMessage() {}

func (x *ClearUnreadResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUnreadResp.ProtoReflect.Descriptor instead.
func (*ClearUnreadResp) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{4}
}

// 批量投递指令:群聊写扩散用,一次 RPC 投多个用户,避免 O(N) 次跨服务调用
type BatchDeliverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`                // 目标用户列表(不含发送方)
	PushType      PushType               `protobuf:"varint,2,opt,name=push_type,json=pushType,proto3,enum=push.PushType" json:"push_type,omitempty"` // 推送方式
	Message       *PushMessage           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                       // 消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeliverReq) Reset() {
	*x = BatchDeliverReq{}
	mi := &file_push_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeliverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeliverReq) ProtoMessage() {}

func (x *BatchDeliverReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeliverReq.ProtoReflect.Descriptor instead.
func (*BatchDeliverReq) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{5}
}

func (x *BatchDeliverReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *BatchDeliverReq) GetPushType() PushType {
	if x != nil {
		return x.PushType
	}
	return PushType_PushTypeUnspecified
}

func (x *BatchDeliverReq) GetMessage() *PushMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type BatchDeliverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 至少一个设备实时投递成功的用户数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeliverResp) Reset() {
	*x = BatchDeliverResp{}
	mi := &file_push_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeliverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeliverResp) ProtoMessage() {}

func (x *BatchDeliverResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeliverResp.ProtoReflect.Descriptor instead.
func (*BatchDeliverResp) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{6}
}

func (x *BatchDeliverResp) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

var File_push_proto protoreflect.FileDescriptor

const file_push_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"push.proto\x12\x04push\"\xe0\x01\n" +
	"\vPushMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\tR\x06convId\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x03R\x05seqId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x03R\amsgType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1b\n" +
	"\tsend_time\x18\a \x01(\x03R\bsendTime\x12\x1b\n" +
	"\tconv_type\x18\b \x01(\bR\bconvType\"\x7f\n" +
	"\n" +
	"DeliverReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12+\n" +
	"\tpush_type\x18\x02 \x01(\x0e2\x0e.push.PushTypeR\bpushType\x12+\n" +
	"\amessage\x18\x03 \x01(\v2\x11.push.PushMessageR\amessage\"'\n" +
	"\vDeliverResp\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"Y\n" +
	"\x0eClearUnreadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\tR\x06convId\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x03R\x05seqId\"\x11\n" +
	"\x0fClearUnreadResp\"\x86\x01\n" +
	"\x0fBatchDeliverReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12+\n" +
	"\tpush_type\x18\x02 \x01(\x0e2\x0e.push.PushTypeR\bpushType\x12+\n" +
	"\amessage\x18\x03 \x01(\v2\x11.push.PushMessageR\amessage\"7\n" +
	"\x10BatchDeliverResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount*I\n" +
	"\bPushType\x12\x17\n" +
	"\x13PushTypeUnspecified\x10\x00\x12\x10\n" +
	"\fPushTypeFull\x10\x01\x12\x12\n" +
	"\x0ePushTypeNotify\x10\x022\xb1\x01\n" +
	"\x04Push\x12.\n" +
	"\aDeliver\x12\x10.push.DeliverReq\x1a\x11.push.DeliverResp\x12=\n" +
	"\fBatchDeliver\x12\x15.push.BatchDeliverReq\x1a\x16.push.BatchDeliverResp\x12:\n" +
	"\vClearUnread\x12\x14.push.ClearUnreadReq\x1a\x15.push.ClearUnreadRespB\bZ\x06./pushb\x06proto3"

var (
	file_push_proto_rawDescOnce sync.Once
	file_push_proto_rawDescData []byte
)

func file_push_proto_rawDescGZIP() []byte {
	file_push_proto_rawDescOnce.Do(func() {
		file_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)))
	})
	return file_push_proto_rawDescData
}

var file_push_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_push_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_push_proto_goTypes = []any{
	(PushType)(0),            // 0: push.PushType
	(*PushMessage)(nil),      // 1: push.PushMessage
	(*DeliverReq)(nil),       // 2: push.DeliverReq
	(*DeliverResp)(nil),      // 3: push.DeliverResp
	(*ClearUnreadReq)(nil),   // 4: push.ClearUnreadReq
	(*ClearUnreadResp)(nil),  // 5: push.ClearUnreadResp
	(*BatchDeliverReq)(nil),  // 6: push.BatchDeliverReq
	(*BatchDeliverResp)(nil), // 7: push.BatchDeliverResp
}
var file_push_proto_depIdxs = []int32{
	0, // 0: push.DeliverReq.push_type:type_name -> push.PushType
	1, // 1: push.DeliverReq.message:type_name -> push.PushMessage
	0, // 2: push.BatchDeliverReq.push_type:type_name -> push.PushType
	1, // 3: push.BatchDeliverReq.message:type_name -> push.PushMessage
	2, // 4: push.Push.Deliver:input_type -> push.DeliverReq
	6, // 5: push.Push.BatchDeliver:input_type -> push.BatchDeliverReq
	4, // 6: push.Push.ClearUnread:input_type -> push.ClearUnreadReq
	3, // 7: push.Push.Deliver:output_type -> push.DeliverResp
	7, // 8: push.Push.BatchDeliver:output_type -> push.BatchDeliverResp
	5, // 9: push.Push.ClearUnread:output_type -> push.ClearUnreadResp
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_push_proto_init() }
func file_push_proto_init() {
	if File_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_proto_goTypes,
		DependencyIndexes: file_push_proto_depIdxs,
		EnumInfos:         file_push_proto_enumTypes,
		MessageInfos:      file_push_proto_msgTypes,
	}.Build()
	File_push_proto = out.File
	file_push_proto_goTypes = nil
	file_push_proto_depIdxs = nil
}
