// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: media.proto

package server

import (
	"context"

	"im-platform/app/media/rpc/internal/logic"
	"im-platform/app/media/rpc/internal/svc"
	"im-platform/app/media/rpc/media"
)

type MediaServer struct {
	svcCtx *svc.ServiceContext
	media.UnimplementedMediaServer
}

func NewMediaServer(svcCtx *svc.ServiceContext) *MediaServer {
	return &MediaServer{
		svcCtx: svcCtx,
	}
}

// 初始化分片上传任务，返回 upload_id 与各分片预签名 URL
func (s *MediaServer) CreateUploadTask(ctx context.Context, in *media.CreateUploadTaskReq) (*media.CreateUploadTaskResp, error) {
	l := logic.NewCreateUploadTaskLogic(ctx, s.svcCtx)
	return l.CreateUploadTask(in)
}

// 客户端所有分片上传完成后调用，触发合并、格式校验、安全审核
func (s *MediaServer) CompleteUpload(ctx context.Context, in *media.CompleteUploadReq) (*media.CompleteUploadResp, error) {
	l := logic.NewCompleteUploadLogic(ctx, s.svcCtx)
	return l.CompleteUpload(in)
}

// 查询文件元数据（含审核状态、缩略图地址）
func (s *MediaServer) GetFileMeta(ctx context.Context, in *media.GetFileMetaReq) (*media.GetFileMetaResp, error) {
	l := logic.NewGetFileMetaLogic(ctx, s.svcCtx)
	return l.GetFileMeta(in)
}

// 重新签发下载预签名 URL（客户端 URL 过期时刷新）
func (s *MediaServer) GeneratePresignedUrl(ctx context.Context, in *media.GeneratePresignedUrlReq) (*media.GeneratePresignedUrlResp, error) {
	l := logic.NewGeneratePresignedUrlLogic(ctx, s.svcCtx)
	return l.GeneratePresignedUrl(in)
}

// 删除文件（物理删除 MinIO + 清理元数据）
func (s *MediaServer) DeleteFile(ctx context.Context, in *media.DeleteFileReq) (*media.DeleteFileResp, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}
