// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// 手工维护:公开路由与鉴权路由两组;新增接口时同步 api/api.api 与 types.go。
// 鉴权组内的 logic 一律从 ctx 取身份(middleware.GetUserID/GetToken),不信任请求体

package handler

import (
	"net/http"

	"im-platform/app/im/api/internal/svc"
	"im-platform/common/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 公开路由:登录/注册/健康检查
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method: http.MethodGet,
				Path:   "/health",
				Handler: func(w http.ResponseWriter, r *http.Request) {
					w.Header().Set("Content-Type", "application/json")
					w.WriteHeader(http.StatusOK)
					_, _ = w.Write([]byte(`{"status":"ok"}`))
				},
			},
		},
	)

	// 业务路由:统一挂鉴权(WithMiddleware 包住路由再展开)
	server.AddRoutes(
		rest.WithMiddleware(middleware.AuthMiddleware(serverCtx.TokenManager),
			// ---- 用户:认证/资料/设备 ----
			rest.Route{Method: http.MethodPost, Path: "/user/logout", Handler: LogoutHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/user/profile", Handler: ProfileHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/profile", Handler: UpdateProfileHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/user/devices", Handler: DevicesHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/device/kick", Handler: KickDeviceHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/password/reset", Handler: ResetPasswordHandler(serverCtx)},
			// ---- 用户:好友 ----
			rest.Route{Method: http.MethodGet, Path: "/user/friends", Handler: FriendsHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/user/friend/applies", Handler: FriendAppliesHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/friend/add", Handler: AddFriendHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/friend/accept", Handler: AcceptFriendHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/friend/delete", Handler: DeleteFriendHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/friend/block", Handler: BlockUserHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/friend/unblock", Handler: UnblockUserHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/user/friend/reject", Handler: RejectFriendHandler(serverCtx)},
			// ---- 群组 ----
			rest.Route{Method: http.MethodPost, Path: "/creategroup", Handler: CreateGroupHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/invitemember", Handler: InviteMemberHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/group/info", Handler: GetGroupInfoHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/group/members", Handler: GetMembersHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/user/groups", Handler: GetUserGroupsHandler(serverCtx)},
			// ---- 群管理(9 个空壳 rpc 已补全) ----
			rest.Route{Method: http.MethodPost, Path: "/group/quit", Handler: QuitGroupHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/group/kick", Handler: KickMemberHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/group/mute", Handler: MuteMemberHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/group/setadmin", Handler: SetAdminHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/group/transfer", Handler: TransferOwnerHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/group/update", Handler: UpdateGroupInfoHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/group/dissolve", Handler: DissolveGroupHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/group/apply", Handler: ApplyJoinGroupHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/group/apply/handle", Handler: HandleApplyHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/group/member-version", Handler: GetMemberVersionHandler(serverCtx)},
			// ---- 消息 ----
			rest.Route{Method: http.MethodPost, Path: "/message/recall", Handler: RecallMessageHandler(serverCtx)},
			// ---- 文件 ----
			rest.Route{Method: http.MethodPost, Path: "/file/upload/task", Handler: CreateUploadTaskHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/file/upload/complete", Handler: CompleteUploadHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/file/meta", Handler: GetFileMetaHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/file/url", Handler: GeneratePresignedUrlHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/file/delete", Handler: DeleteFileHandler(serverCtx)},
		),
	)
}
