// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: group.proto

package groupclient

import (
	"context"

	"im-platform/app/group/rpc/group"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyJoinGroupReq    = group.ApplyJoinGroupReq
	ApplyJoinGroupResp   = group.ApplyJoinGroupResp
	CheckMemberReq       = group.CheckMemberReq
	CheckMemberResp      = group.CheckMemberResp
	CreateGroupReq       = group.CreateGroupReq
	CreateGroupResp      = group.CreateGroupResp
	DissolveGroupReq     = group.DissolveGroupReq
	DissolveGroupResp    = group.DissolveGroupResp
	GetGroupInfoReq      = group.GetGroupInfoReq
	GetGroupInfoResp     = group.GetGroupInfoResp
	GetMemberVersionReq  = group.GetMemberVersionReq
	GetMemberVersionResp = group.GetMemberVersionResp
	GetMembersReq        = group.GetMembersReq
	GetMembersResp       = group.GetMembersResp
	GetUserGroupsReq     = group.GetUserGroupsReq
	GetUserGroupsResp    = group.GetUserGroupsResp
	GroupInfo            = group.GroupInfo
	HandleApplyReq       = group.HandleApplyReq
	HandleApplyResp      = group.HandleApplyResp
	InviteMemberReq      = group.InviteMemberReq
	InviteMemberResp     = group.InviteMemberResp
	KickMemberReq        = group.KickMemberReq
	KickMemberResp       = group.KickMemberResp
	MemberInfo           = group.MemberInfo
	MuteMemberReq        = group.MuteMemberReq
	MuteMemberResp       = group.MuteMemberResp
	QuitGroupReq         = group.QuitGroupReq
	QuitGroupResp        = group.QuitGroupResp
	SetAdminReq          = group.SetAdminReq
	SetAdminResp         = group.SetAdminResp
	TransferOwnerReq     = group.TransferOwnerReq
	TransferOwnerResp    = group.TransferOwnerResp
	UpdateGroupInfoReq   = group.UpdateGroupInfoReq
	UpdateGroupInfoResp  = group.UpdateGroupInfoResp

	Group interface {
		// ==================== 群生命周期 ====================
		CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
		DissolveGroup(ctx context.Context, in *DissolveGroupReq, opts ...grpc.CallOption) (*DissolveGroupResp, error)
		TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error)
		UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoReq, opts ...grpc.CallOption) (*UpdateGroupInfoResp, error)
		GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
		// ==================== 成员管理 ====================
		InviteMember(ctx context.Context, in *InviteMemberReq, opts ...grpc.CallOption) (*InviteMemberResp, error)
		ApplyJoinGroup(ctx context.Context, in *ApplyJoinGroupReq, opts ...grpc.CallOption) (*ApplyJoinGroupResp, error)
		HandleApply(ctx context.Context, in *HandleApplyReq, opts ...grpc.CallOption) (*HandleApplyResp, error)
		KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error)
		QuitGroup(ctx context.Context, in *QuitGroupReq, opts ...grpc.CallOption) (*QuitGroupResp, error)
		MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error)
		SetAdmin(ctx context.Context, in *SetAdminReq, opts ...grpc.CallOption) (*SetAdminResp, error)
		// ==================== 查询接口（供 Message 服务调用） ====================
		GetMembers(ctx context.Context, in *GetMembersReq, opts ...grpc.CallOption) (*GetMembersResp, error)
		CheckMember(ctx context.Context, in *CheckMemberReq, opts ...grpc.CallOption) (*CheckMemberResp, error)
		GetMemberVersion(ctx context.Context, in *GetMemberVersionReq, opts ...grpc.CallOption) (*GetMemberVersionResp, error)
		// 用户所在的群 ID 列表(断线重连补拉时组装会话列表用)
		GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error)
	}

	defaultGroup struct {
		cli zrpc.Client
	}
)

func NewGroup(cli zrpc.Client) Group {
	return &defaultGroup{
		cli: cli,
	}
}

// ==================== 群生命周期 ====================
func (m *defaultGroup) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultGroup) DissolveGroup(ctx context.Context, in *DissolveGroupReq, opts ...grpc.CallOption) (*DissolveGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.DissolveGroup(ctx, in, opts...)
}

func (m *defaultGroup) TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.TransferOwner(ctx, in, opts...)
}

func (m *defaultGroup) UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoReq, opts ...grpc.CallOption) (*UpdateGroupInfoResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.UpdateGroupInfo(ctx, in, opts...)
}

func (m *defaultGroup) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroupInfo(ctx, in, opts...)
}

// ==================== 成员管理 ====================
func (m *defaultGroup) InviteMember(ctx context.Context, in *InviteMemberReq, opts ...grpc.CallOption) (*InviteMemberResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.InviteMember(ctx, in, opts...)
}

func (m *defaultGroup) ApplyJoinGroup(ctx context.Context, in *ApplyJoinGroupReq, opts ...grpc.CallOption) (*ApplyJoinGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.ApplyJoinGroup(ctx, in, opts...)
}

func (m *defaultGroup) HandleApply(ctx context.Context, in *HandleApplyReq, opts ...grpc.CallOption) (*HandleApplyResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.HandleApply(ctx, in, opts...)
}

func (m *defaultGroup) KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.KickMember(ctx, in, opts...)
}

func (m *defaultGroup) QuitGroup(ctx context.Context, in *QuitGroupReq, opts ...grpc.CallOption) (*QuitGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.QuitGroup(ctx, in, opts...)
}

func (m *defaultGroup) MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.MuteMember(ctx, in, opts...)
}

func (m *defaultGroup) SetAdmin(ctx context.Context, in *SetAdminReq, opts ...grpc.CallOption) (*SetAdminResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.SetAdmin(ctx, in, opts...)
}

// ==================== 查询接口（供 Message 服务调用） ====================
func (m *defaultGroup) GetMembers(ctx context.Context, in *GetMembersReq, opts ...grpc.CallOption) (*GetMembersResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetMembers(ctx, in, opts...)
}

func (m *defaultGroup) CheckMember(ctx context.Context, in *CheckMemberReq, opts ...grpc.CallOption) (*CheckMemberResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.CheckMember(ctx, in, opts...)
}

func (m *defaultGroup) GetMemberVersion(ctx context.Context, in *GetMemberVersionReq, opts ...grpc.CallOption) (*GetMemberVersionResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetMemberVersion(ctx, in, opts...)
}

// 用户所在的群 ID 列表(断线重连补拉时组装会话列表用)
func (m *defaultGroup) GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetUserGroups(ctx, in, opts...)
}
