// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: media.proto

package mediaclient

import (
	"context"

	"im-platform/app/media/rpc/media"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuditResult              = media.AuditResult
	ChunkUploadInfo          = media.ChunkUploadInfo
	CompleteUploadReq        = media.CompleteUploadReq
	CompleteUploadResp       = media.CompleteUploadResp
	CreateUploadTaskReq      = media.CreateUploadTaskReq
	CreateUploadTaskResp     = media.CreateUploadTaskResp
	DeleteFileReq            = media.DeleteFileReq
	DeleteFileResp           = media.DeleteFileResp
	GeneratePresignedUrlReq  = media.GeneratePresignedUrlReq
	GeneratePresignedUrlResp = media.GeneratePresignedUrlResp
	GetFileMetaReq           = media.GetFileMetaReq
	GetFileMetaResp          = media.GetFileMetaResp

	Media interface {
		// 初始化分片上传任务，返回 upload_id 与各分片预签名 URL
		CreateUploadTask(ctx context.Context, in *CreateUploadTaskReq, opts ...grpc.CallOption) (*CreateUploadTaskResp, error)
		// 客户端所有分片上传完成后调用，触发合并、格式校验、安全审核
		CompleteUpload(ctx context.Context, in *CompleteUploadReq, opts ...grpc.CallOption) (*CompleteUploadResp, error)
		// 查询文件元数据（含审核状态、缩略图地址）
		GetFileMeta(ctx context.Context, in *GetFileMetaReq, opts ...grpc.CallOption) (*GetFileMetaResp, error)
		// 重新签发下载预签名 URL（客户端 URL 过期时刷新）
		GeneratePresignedUrl(ctx context.Context, in *GeneratePresignedUrlReq, opts ...grpc.CallOption) (*GeneratePresignedUrlResp, error)
		// 删除文件（物理删除 MinIO + 清理元数据）
		DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileResp, error)
	}

	defaultMedia struct {
		cli zrpc.Client
	}
)

func NewMedia(cli zrpc.Client) Media {
	return &defaultMedia{
		cli: cli,
	}
}

// 初始化分片上传任务，返回 upload_id 与各分片预签名 URL
func (m *defaultMedia) CreateUploadTask(ctx context.Context, in *CreateUploadTaskReq, opts ...grpc.CallOption) (*CreateUploadTaskResp, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.CreateUploadTask(ctx, in, opts...)
}

// 客户端所有分片上传完成后调用，触发合并、格式校验、安全审核
func (m *defaultMedia) CompleteUpload(ctx context.Context, in *CompleteUploadReq, opts ...grpc.CallOption) (*CompleteUploadResp, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.CompleteUpload(ctx, in, opts...)
}

// 查询文件元数据（含审核状态、缩略图地址）
func (m *defaultMedia) GetFileMeta(ctx context.Context, in *GetFileMetaReq, opts ...grpc.CallOption) (*GetFileMetaResp, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.GetFileMeta(ctx, in, opts...)
}

// 重新签发下载预签名 URL（客户端 URL 过期时刷新）
func (m *defaultMedia) GeneratePresignedUrl(ctx context.Context, in *GeneratePresignedUrlReq, opts ...grpc.CallOption) (*GeneratePresignedUrlResp, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.GeneratePresignedUrl(ctx, in, opts...)
}

// 删除文件（物理删除 MinIO + 清理元数据）
func (m *defaultMedia) DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileResp, error) {
	client := media.NewMediaClient(m.cli.Conn())
	return client.DeleteFile(ctx, in, opts...)
}
