// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginReq struct {
	Phone      string `json:"phone" validate:"omitempty"`
	Email      string `json:"email" validate:"omitempty"`
	Account    string `json:"account" validate:"omitempty"`
	DeviceType int32  `json:"devicetype" validate:"omitempty"`
	DeviceId   string `json:"deviceid" validate:"omitempty"`
	Password   string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Phone    string `json:"phone" validate:"omitempty"`
	Email    string `json:"email" validate:"omitempty"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Account  int64  `json:"account" validate:"omitempty"`
	Password string `json:"password"`
}
