// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	devicesFieldNames          = builder.RawFieldNames(&Devices{}, true)
	devicesRows                = strings.Join(devicesFieldNames, ",")
	devicesRowsExpectAutoSet   = strings.Join(stringx.Remove(devicesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	devicesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(devicesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicDevicesIdPrefix = "cache:public:devices:id:"
)

type (
	devicesModel interface {
		Insert(ctx context.Context, data *Devices) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Devices, error)
		Update(ctx context.Context, data *Devices) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDevicesModel struct {
		sqlc.CachedConn
		table string
	}

	Devices struct {
		Id               int64          `db:"id"`
		Userid           int64          `db:"userid"`
		Devicetype       int32          `db:"devicetype"`
		Devicename       sql.NullString `db:"devicename"`
		Deviceid         string         `db:"deviceid"`
		Location         sql.NullString `db:"location"`
		LoginAt          sql.NullTime   `db:"login_at"`
		LogoutAt         sql.NullTime   `db:"logout_at"`
		LastActiveAt     sql.NullTime   `db:"last_active_at"`
		AccessTokenHash  sql.NullString `db:"access_token_hash"`
		RefreshTokenHash sql.NullString `db:"refresh_token_hash"`
		Status           int64          `db:"status"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
	}
)

func newDevicesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDevicesModel {
	return &defaultDevicesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."devices"`,
	}
}

func (m *defaultDevicesModel) Delete(ctx context.Context, id int64) error {
	publicDevicesIdKey := fmt.Sprintf("%s%v", cachePublicDevicesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicDevicesIdKey)
	return err
}

func (m *defaultDevicesModel) FindOne(ctx context.Context, id int64) (*Devices, error) {
	publicDevicesIdKey := fmt.Sprintf("%s%v", cachePublicDevicesIdPrefix, id)
	var resp Devices
	err := m.QueryRowCtx(ctx, &resp, publicDevicesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", devicesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDevicesModel) Insert(ctx context.Context, data *Devices) (sql.Result, error) {
	publicDevicesIdKey := fmt.Sprintf("%s%v", cachePublicDevicesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)", m.table, devicesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Userid, data.Devicetype, data.Devicename, data.Deviceid, data.Location, data.LoginAt, data.LogoutAt, data.LastActiveAt, data.AccessTokenHash, data.RefreshTokenHash, data.Status)
	}, publicDevicesIdKey)
	return ret, err
}

func (m *defaultDevicesModel) Update(ctx context.Context, data *Devices) error {
	publicDevicesIdKey := fmt.Sprintf("%s%v", cachePublicDevicesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, devicesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Userid, data.Devicetype, data.Devicename, data.Deviceid, data.Location, data.LoginAt, data.LogoutAt, data.LastActiveAt, data.AccessTokenHash, data.RefreshTokenHash, data.Status)
	}, publicDevicesIdKey)
	return err
}

func (m *defaultDevicesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicDevicesIdPrefix, primary)
}

func (m *defaultDevicesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", devicesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDevicesModel) tableName() string {
	return m.table
}
