// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendsFieldNames          = builder.RawFieldNames(&Friends{}, true)
	friendsRows                = strings.Join(friendsFieldNames, ",")
	friendsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	friendsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(friendsFieldNames, "friend_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	friendsModel interface {
		Insert(ctx context.Context, data *Friends) (sql.Result, error)
		FindOne(ctx context.Context, friendId int64) (*Friends, error)
		Update(ctx context.Context, data *Friends) error
		Delete(ctx context.Context, friendId int64) error
		// FindFriendsByUserId 已迁移至 friendsmodel.go 自定义实现(原生成版 SQL 损坏)
	}

	defaultFriendsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Friends struct {
		UserId        int64          `db:"user_id"`
		FriendId      int64          `db:"friend_id"`
		Status        int64          `db:"status"`
		FriendGroupId sql.NullInt64  `db:"friend_group_id"`
		Remark        sql.NullString `db:"remark"`
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
	friendInfoRow struct {
		UserId        int64  `db:"user_id"`
		Nickname      string `db:"nickname"`
		Avatar        string `db:"avatar"`
		Remark        string `db:"remark"`
		FriendGroupId int64  `db:"friend_group_id"`
		CreatedAt     int64  `db:"created_at"`
	}
)

func newFriendsModel(conn sqlx.SqlConn) *defaultFriendsModel {
	return &defaultFriendsModel{
		conn:  conn,
		table: `"public"."friends"`,
	}
}

func (m *defaultFriendsModel) Delete(ctx context.Context, friendId int64) error {
	query := fmt.Sprintf("delete from %s where friend_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, friendId)
	return err
}

func (m *defaultFriendsModel) FindOne(ctx context.Context, friendId int64) (*Friends, error) {
	query := fmt.Sprintf("select %s from %s where friend_id = $1 limit 1", friendsRows, m.table)
	var resp Friends
	err := m.conn.QueryRowCtx(ctx, &resp, query, friendId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendsModel) Insert(ctx context.Context, data *Friends) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, friendsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.Status, data.FriendGroupId, data.Remark)
	return ret, err
}

func (m *defaultFriendsModel) Update(ctx context.Context, data *Friends) error {
	query := fmt.Sprintf("update %s set %s where friend_id = $1", m.table, friendsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.FriendId, data.UserId, data.Status, data.FriendGroupId, data.Remark)
	return err
}

func (m *defaultFriendsModel) tableName() string {
	return m.table
}
