// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendgroupsFieldNames          = builder.RawFieldNames(&Friendgroups{}, true)
	friendgroupsRows                = strings.Join(friendgroupsFieldNames, ",")
	friendgroupsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendgroupsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	friendgroupsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(friendgroupsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	friendgroupsModel interface {
		Insert(ctx context.Context, data *Friendgroups) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Friendgroups, error)
		Update(ctx context.Context, data *Friendgroups) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFriendgroupsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Friendgroups struct {
		Id        int64     `db:"id"`
		UserId    int64     `db:"user_id"`
		Name      string    `db:"name"`
		SortOrder int64     `db:"sort_order"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newFriendgroupsModel(conn sqlx.SqlConn) *defaultFriendgroupsModel {
	return &defaultFriendgroupsModel{
		conn:  conn,
		table: `"public"."friendgroups"`,
	}
}

func (m *defaultFriendgroupsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFriendgroupsModel) FindOne(ctx context.Context, id int64) (*Friendgroups, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", friendgroupsRows, m.table)
	var resp Friendgroups
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendgroupsModel) Insert(ctx context.Context, data *Friendgroups) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, friendgroupsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Name, data.SortOrder)
	return ret, err
}

func (m *defaultFriendgroupsModel) Update(ctx context.Context, data *Friendgroups) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, friendgroupsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Name, data.SortOrder)
	return err
}

func (m *defaultFriendgroupsModel) tableName() string {
	return m.table
}
