// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendappliesFieldNames          = builder.RawFieldNames(&Friendapplies{}, true)
	friendappliesRows                = strings.Join(friendappliesFieldNames, ",")
	friendappliesRowsExpectAutoSet   = strings.Join(stringx.Remove(friendappliesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	friendappliesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(friendappliesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	friendappliesModel interface {
		Insert(ctx context.Context, data *Friendapplies) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Friendapplies, error)
		FindOneByApplicantIdTargetId(ctx context.Context, applicantId int64, targetId int64) (*Friendapplies, error)
		Update(ctx context.Context, data *Friendapplies) error
		Delete(ctx context.Context, id int64) error
		FindByTargetWithUserInfo(ctx context.Context, targetId int64, status int32, page, pageSize int32) ([]friendApplyRow, error)
	}

	defaultFriendappliesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Friendapplies struct {
		Id            int64          `db:"id"`
		ApplicantId   int64          `db:"applicant_id"`
		TargetId      int64          `db:"target_id"`
		ApplyReason   sql.NullString `db:"apply_reason"`
		Status        int64          `db:"status"`
		HandlerRemark sql.NullString `db:"handler_remark"`
		CreatedAt     time.Time      `db:"created_at"`
		HandledAt     sql.NullTime   `db:"handled_at"`
	}
	friendApplyRow struct {
		Id                int64  `db:"id"`
		ApplicantId       int64  `db:"applicant_id"`
		ApplicantNickname string `db:"applicant_nickname"`
		ApplicantAvatar   string `db:"applicant_avatar"`
		TargetId          int64  `db:"target_id"`
		ApplyReason       string `db:"apply_reason"`
		Status            int32  `db:"status"`
		CreatedAt         int64  `db:"created_at"`
		HandledAt         int64  `db:"handled_at"`
	}
)

func newFriendappliesModel(conn sqlx.SqlConn) *defaultFriendappliesModel {
	return &defaultFriendappliesModel{
		conn:  conn,
		table: `"public"."friendapplies"`,
	}
}

func (m *defaultFriendappliesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFriendappliesModel) FindOne(ctx context.Context, id int64) (*Friendapplies, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", friendappliesRows, m.table)
	var resp Friendapplies
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendappliesModel) FindOneByApplicantIdTargetId(ctx context.Context, applicantId int64, targetId int64) (*Friendapplies, error) {
	var resp Friendapplies
	query := fmt.Sprintf("select %s from %s where applicant_id = $1 and target_id = $2 limit 1", friendappliesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, applicantId, targetId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendappliesModel) Insert(ctx context.Context, data *Friendapplies) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, friendappliesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ApplicantId, data.TargetId, data.ApplyReason, data.Status, data.HandlerRemark, data.HandledAt)
	return ret, err
}

func (m *defaultFriendappliesModel) Update(ctx context.Context, newData *Friendapplies) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, friendappliesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ApplicantId, newData.TargetId, newData.ApplyReason, newData.Status, newData.HandlerRemark, newData.HandledAt)
	return err
}

func (m *defaultFriendappliesModel) FindByTargetWithUserInfo(ctx context.Context, targetId int64, status int32, page, pageSize int32) ([]friendApplyRow, error) {
	offset := (page - 1) * pageSize
	query := fmt.Sprintf(`
        SELECT 
            fa.id,
            fa.applicant_id,
            COALESCE(u.nickname, '') AS applicant_nickname,
            COALESCE(u.avatar, '') AS applicant_avatar,
            fa.target_id,
            fa.apply_reason,
            fa.status,
            EXTRACT(epoch FROM fa.created_at) * 1000 AS created_at,
            EXTRACT(epoch FROM fa.handled_at) * 1000 AS handled_at
        FROM %s fa
        LEFT JOIN users u ON fa.applicant_id = u.id
        WHERE fa.target_id = $1 AND fa.status = $2
        ORDER BY fa.created_at DESC
        LIMIT $3 OFFSET $4
    `, m.table)

	var rows []friendApplyRow
	err := m.conn.QueryRowsCtx(ctx, &rows, query, targetId, status, pageSize, offset)
	if err != nil {
		return nil, err
	}
	return rows, nil
}

func (m *defaultFriendappliesModel) tableName() string {
	return m.table
}
