// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	filesFieldNames          = builder.RawFieldNames(&Files{}, true)
	filesRows                = strings.Join(filesFieldNames, ",")
	filesRowsExpectAutoSet   = strings.Join(stringx.Remove(filesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	filesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(filesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	filesModel interface {
		Insert(ctx context.Context, data *Files) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Files, error)
		Update(ctx context.Context, data *Files) error
		Delete(ctx context.Context, id string) error
	}

	defaultFilesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Files struct {
		Id          string         `db:"id"` // 雪花 file_id(字符串)
		FileName    string         `db:"file_name"`
		FileSize    int64          `db:"file_size"`
		MimeType    string         `db:"mime_type"`
		FileType    int64          `db:"file_type"` // 1-图片 2-语音 3-视频 4-文件
		UploaderId  int64          `db:"uploader_id"`
		UploadTime  time.Time      `db:"upload_time"`
		Status      int64          `db:"status"` // 1-正常 2-审核中 3-审核拒绝 4-已删除
		ObjectKey   string         `db:"object_key"`
		Bucket      string         `db:"bucket"`
		Thumbnails  sql.NullString `db:"thumbnails"`   // 缩略图 JSON
		AuditType   sql.NullInt64  `db:"audit_type"`   // 审核类型
		AuditStatus sql.NullInt64  `db:"audit_status"` // 审核结果状态
		AuditDetail sql.NullString `db:"audit_detail"`
		AuditedAt   sql.NullTime   `db:"audited_at"`
	}
)

func newFilesModel(conn sqlx.SqlConn) *defaultFilesModel {
	return &defaultFilesModel{
		conn:  conn,
		table: `"public"."files"`,
	}
}

func (m *defaultFilesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFilesModel) FindOne(ctx context.Context, id string) (*Files, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", filesRows, m.table)
	var resp Files
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFilesModel) Insert(ctx context.Context, data *Files) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)", m.table, filesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.FileName, data.FileSize, data.MimeType, data.FileType, data.UploaderId, data.UploadTime, data.Status, data.ObjectKey, data.Bucket, data.Thumbnails, data.AuditType, data.AuditStatus, data.AuditDetail, data.AuditedAt)
	return ret, err
}

func (m *defaultFilesModel) Update(ctx context.Context, data *Files) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, filesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.FileName, data.FileSize, data.MimeType, data.FileType, data.UploaderId, data.UploadTime, data.Status, data.ObjectKey, data.Bucket, data.Thumbnails, data.AuditType, data.AuditStatus, data.AuditDetail, data.AuditedAt)
	return err
}

func (m *defaultFilesModel) tableName() string {
	return m.table
}
