// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: gateway.proto

package server

import (
	"context"

	"im-platform/app/gateway/rpc/gateway"
	"im-platform/app/gateway/rpc/internal/conn"
	"im-platform/app/gateway/rpc/internal/protocol"
	"im-platform/app/gateway/rpc/internal/svc"

	"github.com/zeromicro/go-zero/core/logx"
)

type GatewayServer struct {
	svcCtx *svc.ServiceContext
	gateway.UnimplementedGatewayServer
}

func NewGatewayServer(svcCtx *svc.ServiceContext) *GatewayServer {
	return &GatewayServer{
		svcCtx: svcCtx,
	}
}

// PushToConn 实时推送单用户单设备。
// 返回值语义:Success=true 仅表示"消息已进入存活连接的发送队列",
// 不保证客户端收到——Send 与 Close 之间的竞态窗口内入队的消息会随连接死亡而丢失。
// push 侧依赖本返回值决定是否转离线信箱(at-least-once 兜底),失败必须转,成功不回执。
func (s *GatewayServer) PushToConn(ctx context.Context, in *gateway.PushToConnReq) (*gateway.PushToConnResp, error) {
	c, _ := s.svcCtx.ConnManager.Get(in.UserId, in.DeviceType)
	if c == nil {
		logx.Infof("推送失败,连接不存在 | rpc=PushToConn user=%d device=%d", in.UserId, in.DeviceType)
		return &gateway.PushToConnResp{
			Success:  false,
			ErrorMsg: "conn not found",
		}, nil
	}

	// 下行必须封帧(与上行 DecodeFrame 对称),否则客户端无法识别帧类型
	frame := protocol.EncodeFrame(protocol.FramePush, in.Payload)
	switch res := c.Send(frame); res {
	case conn.SendOK:
		return &gateway.PushToConnResp{Success: true}, nil
	case conn.SendClosed:
		// 连接已关闭:必须返回失败,让 push 服务把消息转入离线箱;
		// 原实现漏了 return,落到 Success:true,消息永久丢失
		logx.Infof("推送失败,连接已关闭 | rpc=PushToConn user=%d device=%d", in.UserId, in.DeviceType)
		return &gateway.PushToConnResp{
			Success:  false,
			ErrorMsg: "conn closed",
		}, nil
	case conn.SendQueueFull:
		logx.Infof("推送失败,发送队列已满 | rpc=PushToConn user=%d device=%d", in.UserId, in.DeviceType)
		return &gateway.PushToConnResp{
			Success:  false,
			ErrorMsg: "queue full",
		}, nil
	default:
		return &gateway.PushToConnResp{
			Success:  false,
			ErrorMsg: "unknown",
		}, nil
	}
}

// BatchPushToConn 群聊写扩散的批量推送入口:一次 RPC 推多个用户,
// 在本网关进程内逐用户逐设备下发,替代消息服务 O(N) 次跨服务 Deliver
func (s *GatewayServer) BatchPushToConn(ctx context.Context, in *gateway.BatchPushToConnReq) (*gateway.BatchPushToConnResp, error) {
	// 下行统一封帧,与 PushToConn 对称
	frame := protocol.EncodeFrame(protocol.FramePush, in.Payload)
	var (
		successCount int32
		failed       []int64
	)
	for _, uid := range in.UserIds {
		conns := s.svcCtx.ConnManager.GetByUser(uid)
		if len(conns) == 0 {
			failed = append(failed, uid)
			continue
		}
		delivered := false
		for _, c := range conns {
			if c.Send(frame) == conn.SendOK {
				successCount++
				delivered = true
			}
		}
		if !delivered {
			failed = append(failed, uid)
		}
	}
	return &gateway.BatchPushToConnResp{
		SuccessCount:  successCount,
		FailedUserIds: failed,
	}, nil
}
