// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: gateway.proto

package server

import (
	"context"

	"im-platform/app/gateway/rpc/gateway"
	"im-platform/app/gateway/rpc/internal/logic"
	"im-platform/app/gateway/rpc/internal/svc"
)

type GatewayServer struct {
	svcCtx *svc.ServiceContext
	gateway.UnimplementedGatewayServer
}

func NewGatewayServer(svcCtx *svc.ServiceContext) *GatewayServer {
	return &GatewayServer{
		svcCtx: svcCtx,
	}
}

func (s *GatewayServer) PushToConn(ctx context.Context, in *gateway.PushToConnReq) (*gateway.PushToConnResp, error) {
	l := logic.NewPushToConnLogic(ctx, s.svcCtx)
	return l.PushToConn(in)
}

// 批量推送:一次 RPC 推多个用户(群聊写扩散用,避免 O(N) 次 Deliver)
func (s *GatewayServer) BatchPushToConn(ctx context.Context, in *gateway.BatchPushToConnReq) (*gateway.BatchPushToConnResp, error) {
	l := logic.NewBatchPushToConnLogic(ctx, s.svcCtx)
	return l.BatchPushToConn(in)
}
