syntax ="proto3";

package user;

option go_package = "./user";


message RegisterRequest {
    string phone = 1;
    string password = 2;
    string email = 3; 
}

message RegisterResponse {
    int64 account = 2;
}

message LoginRequest {
    string phone = 1;
    string email = 2;
    string account = 3;

    string password = 4;
    int32 devicetype =5;
    string deviceid =6;
}

message LoginResponse {
    int64 userid = 1;
}

service User {
    rpc Login (LoginRequest) returns (LoginResponse);
    rpc Register (RegisterRequest) returns (RegisterResponse);
}