// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	inboxesFieldNames          = builder.RawFieldNames(&Inboxes{}, true)
	inboxesRows                = strings.Join(inboxesFieldNames, ",")
	inboxesRowsExpectAutoSet   = strings.Join(stringx.Remove(inboxesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	inboxesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(inboxesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicInboxesIdPrefix = "cache:public:inboxes:id:"
)

type (
	inboxesModel interface {
		Insert(ctx context.Context, data *Inboxes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Inboxes, error)
		Update(ctx context.Context, data *Inboxes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultInboxesModel struct {
		sqlc.CachedConn
		table string
	}

	Inboxes struct {
		Id        int64        `db:"id"`
		Userid    int64        `db:"userid"`
		Msgid     int64        `db:"msgid"`
		Convid    string       `db:"convid"`
		Seqid     int64        `db:"seqid"`
		Isread    bool         `db:"isread"`
		Readtime  sql.NullTime `db:"readtime"`
		Status    int64        `db:"status"`
		CreatedAt time.Time    `db:"created_at"`
	}
)

func newInboxesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInboxesModel {
	return &defaultInboxesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."inboxes"`,
	}
}

func (m *defaultInboxesModel) Delete(ctx context.Context, id int64) error {
	publicInboxesIdKey := fmt.Sprintf("%s%v", cachePublicInboxesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicInboxesIdKey)
	return err
}

func (m *defaultInboxesModel) FindOne(ctx context.Context, id int64) (*Inboxes, error) {
	publicInboxesIdKey := fmt.Sprintf("%s%v", cachePublicInboxesIdPrefix, id)
	var resp Inboxes
	err := m.QueryRowCtx(ctx, &resp, publicInboxesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", inboxesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInboxesModel) Insert(ctx context.Context, data *Inboxes) (sql.Result, error) {
	publicInboxesIdKey := fmt.Sprintf("%s%v", cachePublicInboxesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, inboxesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Userid, data.Msgid, data.Convid, data.Seqid, data.Isread, data.Readtime, data.Status)
	}, publicInboxesIdKey)
	return ret, err
}

func (m *defaultInboxesModel) Update(ctx context.Context, data *Inboxes) error {
	publicInboxesIdKey := fmt.Sprintf("%s%v", cachePublicInboxesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, inboxesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Userid, data.Msgid, data.Convid, data.Seqid, data.Isread, data.Readtime, data.Status)
	}, publicInboxesIdKey)
	return err
}

func (m *defaultInboxesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicInboxesIdPrefix, primary)
}

func (m *defaultInboxesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", inboxesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInboxesModel) tableName() string {
	return m.table
}
