// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messagesFieldNames          = builder.RawFieldNames(&Messages{}, true)
	messagesRows                = strings.Join(messagesFieldNames, ",")
	messagesRowsExpectAutoSet   = strings.Join(stringx.Remove(messagesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	messagesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(messagesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicMessagesIdPrefix          = "cache:public:messages:id:"
	cachePublicMessagesClientmsgidPrefix = "cache:public:messages:clientmsgid:"
	cachePublicMessagesConvidSeqidPrefix = "cache:public:messages:convid:seqid:"
)

type (
	messagesModel interface {
		Insert(ctx context.Context, data *Messages) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Messages, error)
		FindOneByClientmsgid(ctx context.Context, clientmsgid string) (*Messages, error)
		FindOneByConvidSeqid(ctx context.Context, convid string, seqid int64) (*Messages, error)
		Update(ctx context.Context, data *Messages) error
		Delete(ctx context.Context, id int64) error
		BatchGetByIds(ctx context.Context, convid string, msgIds []int64) ([]*Messages, error)
		FindBySeqRange(ctx context.Context, convid string, startSeq, endSeq, limit int64) ([]*Messages, error)
		FindByClientMsgId(ctx context.Context, convid string, clientmsgid string) (*Messages, error)
	}

	defaultMessagesModel struct {
		sqlc.CachedConn
		table string
	}

	Messages struct {
		Id          int64          `db:"id"`
		Convid      string         `db:"convid"`
		Clientmsgid string         `db:"clientmsgid"`
		Senderid    int64          `db:"senderid"`
		Msgtype     int64          `db:"msgtype"`
		Content     string         `db:"content"`
		Seqid       int64          `db:"seqid"`
		Sendtime    time.Time      `db:"sendtime"`
		Status      int64          `db:"status"`
		Recalledby  sql.NullInt64  `db:"recalledby"`
		RecalledAt  sql.NullTime   `db:"recalled_at"`
		Extra       sql.NullString `db:"extra"`
		CreatedAt   time.Time      `db:"created_at"`
	}
)

func newMessagesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMessagesModel {
	return &defaultMessagesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."messages"`,
	}
}

func (m *defaultMessagesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicMessagesClientmsgidKey := fmt.Sprintf("%s%v", cachePublicMessagesClientmsgidPrefix, data.Clientmsgid)
	publicMessagesConvidSeqidKey := fmt.Sprintf("%s%v:%v", cachePublicMessagesConvidSeqidPrefix, data.Convid, data.Seqid)
	publicMessagesIdKey := fmt.Sprintf("%s%v", cachePublicMessagesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicMessagesClientmsgidKey, publicMessagesConvidSeqidKey, publicMessagesIdKey)
	return err
}

func (m *defaultMessagesModel) FindOne(ctx context.Context, id int64) (*Messages, error) {
	publicMessagesIdKey := fmt.Sprintf("%s%v", cachePublicMessagesIdPrefix, id)
	var resp Messages
	err := m.QueryRowCtx(ctx, &resp, publicMessagesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", messagesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) FindOneByClientmsgid(ctx context.Context, clientmsgid string) (*Messages, error) {
	publicMessagesClientmsgidKey := fmt.Sprintf("%s%v", cachePublicMessagesClientmsgidPrefix, clientmsgid)
	var resp Messages
	err := m.QueryRowIndexCtx(ctx, &resp, publicMessagesClientmsgidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where clientmsgid = $1 limit 1", messagesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, clientmsgid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) FindOneByConvidSeqid(ctx context.Context, convid string, seqid int64) (*Messages, error) {
	publicMessagesConvidSeqidKey := fmt.Sprintf("%s%v:%v", cachePublicMessagesConvidSeqidPrefix, convid, seqid)
	var resp Messages
	err := m.QueryRowIndexCtx(ctx, &resp, publicMessagesConvidSeqidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where convid = $1 and seqid = $2 limit 1", messagesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, convid, seqid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) Insert(ctx context.Context, data *Messages) (sql.Result, error) {
	publicMessagesClientmsgidKey := fmt.Sprintf("%s%v", cachePublicMessagesClientmsgidPrefix, data.Clientmsgid)
	publicMessagesConvidSeqidKey := fmt.Sprintf("%s%v:%v", cachePublicMessagesConvidSeqidPrefix, data.Convid, data.Seqid)
	publicMessagesIdKey := fmt.Sprintf("%s%v", cachePublicMessagesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)", m.table, messagesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Convid, data.Clientmsgid, data.Senderid, data.Msgtype, data.Content, data.Seqid, data.Sendtime, data.Status, data.Recalledby, data.RecalledAt, data.Extra)
	}, publicMessagesClientmsgidKey, publicMessagesConvidSeqidKey, publicMessagesIdKey)
	return ret, err
}

func (m *defaultMessagesModel) Update(ctx context.Context, newData *Messages) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicMessagesClientmsgidKey := fmt.Sprintf("%s%v", cachePublicMessagesClientmsgidPrefix, data.Clientmsgid)
	publicMessagesConvidSeqidKey := fmt.Sprintf("%s%v:%v", cachePublicMessagesConvidSeqidPrefix, data.Convid, data.Seqid)
	publicMessagesIdKey := fmt.Sprintf("%s%v", cachePublicMessagesIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, messagesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.Convid, newData.Clientmsgid, newData.Senderid, newData.Msgtype, newData.Content, newData.Seqid, newData.Sendtime, newData.Status, newData.Recalledby, newData.RecalledAt, newData.Extra)
	}, publicMessagesClientmsgidKey, publicMessagesConvidSeqidKey, publicMessagesIdKey)
	return err
}

func (m *defaultMessagesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicMessagesIdPrefix, primary)
}

func (m *defaultMessagesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", messagesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMessagesModel) tableName() string {
	return m.table
}

func (m *defaultMessagesModel) FindByClientMsgId(ctx context.Context, convid string, clientmsgid string) (*Messages, error) {
	var resp Messages
	query := fmt.Sprintf("select %s from %s where convid = $1 and clientmsgid = $2 limit 1", messagesRows, m.table)
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, convid, clientmsgid)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) BatchGetByIds(ctx context.Context, convid string, msgIds []int64) ([]*Messages, error) {
	if len(msgIds) == 0 {
		return nil, nil
	}

	placeholders := make([]string, len(msgIds))
	args := make([]any, 0, len(msgIds)+1)
	args = append(args, convid)
	for i, id := range msgIds {
		placeholders[i] = fmt.Sprintf("$%d", i+2)
		args = append(args, id)
	}

	var resp []*Messages
	query := fmt.Sprintf("select %s from %s where convid = $1 and id in (%s) order by seqid asc",
		messagesRows, m.table, strings.Join(placeholders, ","))
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessagesModel) FindBySeqRange(ctx context.Context, convid string, startSeq, endSeq, limit int64) ([]*Messages, error) {
	var resp []*Messages
	query := fmt.Sprintf("select %s from %s where convid = $1 and seqid between $2 and $3 order by seqid asc limit $4",
		messagesRows, m.table)
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, convid, startSeq, endSeq, limit)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, nil // 区间内无消息是正常情况（新会话/全被清理），不是错误
	default:
		return nil, err
	}
}
