// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seqsFieldNames          = builder.RawFieldNames(&Seqs{}, true)
	seqsRows                = strings.Join(seqsFieldNames, ",")
	seqsRowsExpectAutoSet   = strings.Join(stringx.Remove(seqsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	seqsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(seqsFieldNames, "conv_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicSeqsConvIdPrefix = "cache:public:seqs:convId:"
)

type (
	seqsModel interface {
		Insert(ctx context.Context, data *Seqs) (sql.Result, error)
		FindOne(ctx context.Context, convId string) (*Seqs, error)
		Update(ctx context.Context, data *Seqs) error
		Delete(ctx context.Context, convId string) error
	}

	defaultSeqsModel struct {
		sqlc.CachedConn
		table string
	}

	Seqs struct {
		ConvId    string    `db:"conv_id"`
		MaxSeq    int64     `db:"max_seq"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newSeqsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSeqsModel {
	return &defaultSeqsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."seqs"`,
	}
}

func (m *defaultSeqsModel) Delete(ctx context.Context, convId string) error {
	publicSeqsConvIdKey := fmt.Sprintf("%s%v", cachePublicSeqsConvIdPrefix, convId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where conv_id = $1", m.table)
		return conn.ExecCtx(ctx, query, convId)
	}, publicSeqsConvIdKey)
	return err
}

func (m *defaultSeqsModel) FindOne(ctx context.Context, convId string) (*Seqs, error) {
	publicSeqsConvIdKey := fmt.Sprintf("%s%v", cachePublicSeqsConvIdPrefix, convId)
	var resp Seqs
	err := m.QueryRowCtx(ctx, &resp, publicSeqsConvIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where conv_id = $1 limit 1", seqsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, convId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeqsModel) Insert(ctx context.Context, data *Seqs) (sql.Result, error) {
	publicSeqsConvIdKey := fmt.Sprintf("%s%v", cachePublicSeqsConvIdPrefix, data.ConvId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, seqsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ConvId, data.MaxSeq)
	}, publicSeqsConvIdKey)
	return ret, err
}

func (m *defaultSeqsModel) Update(ctx context.Context, data *Seqs) error {
	publicSeqsConvIdKey := fmt.Sprintf("%s%v", cachePublicSeqsConvIdPrefix, data.ConvId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where conv_id = $1", m.table, seqsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ConvId, data.MaxSeq)
	}, publicSeqsConvIdKey)
	return err
}

func (m *defaultSeqsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicSeqsConvIdPrefix, primary)
}

func (m *defaultSeqsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where conv_id = $1 limit 1", seqsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSeqsModel) tableName() string {
	return m.table
}
