// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seqsFieldNames          = builder.RawFieldNames(&Seqs{}, true)
	seqsRows                = strings.Join(seqsFieldNames, ",")
	seqsRowsExpectAutoSet   = strings.Join(stringx.Remove(seqsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	seqsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(seqsFieldNames, "conv_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	seqsModel interface {
		Insert(ctx context.Context, data *Seqs) (sql.Result, error)
		FindOne(ctx context.Context, convId string) (*Seqs, error)
		Update(ctx context.Context, data *Seqs) error
		Delete(ctx context.Context, convId string) error
		IncrSeq(ctx context.Context, convId string) (int64, error)
	}

	defaultSeqsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Seqs struct {
		ConvId    string    `db:"conv_id"`
		MaxSeq    int64     `db:"max_seq"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newSeqsModel(conn sqlx.SqlConn) *defaultSeqsModel {
	return &defaultSeqsModel{
		conn:  conn,
		table: `"public"."seqs"`,
	}
}

func (m *defaultSeqsModel) Delete(ctx context.Context, convId string) error {
	query := fmt.Sprintf("delete from %s where conv_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, convId)
	return err
}

func (m *defaultSeqsModel) FindOne(ctx context.Context, convId string) (*Seqs, error) {
	query := fmt.Sprintf("select %s from %s where conv_id = $1 limit 1", seqsRows, m.table)
	var resp Seqs
	err := m.conn.QueryRowCtx(ctx, &resp, query, convId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeqsModel) Insert(ctx context.Context, data *Seqs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, seqsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConvId, data.MaxSeq)
	return ret, err
}

func (m *defaultSeqsModel) Update(ctx context.Context, data *Seqs) error {
	query := fmt.Sprintf("update %s set %s where conv_id = $1", m.table, seqsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ConvId, data.MaxSeq)
	return err
}

func (m *defaultSeqsModel) tableName() string {
	return m.table
}

// IncrSeq "+1 分配器":行锁递增 seqs.max_seq 并返回新值。
// 仅限 Redis 故障时的 PG 兜底分配(allocateFromPG)使用,持久化路径一律走 UpsertMaxSeq;
// 原名 CustomQueryRowCtx 完全名不副实,曾导致消费端误用使 PG 与 Redis 永久脱节,已更名
func (m *defaultSeqsModel) IncrSeq(ctx context.Context, convId string) (int64, error) {
	var res int64
	query := `
	INSERT INTO seqs (conv_id, max_seq, updated_at)
		VALUES ($1, 1, NOW())
		ON CONFLICT (conv_id) DO UPDATE
		SET max_seq = seqs.max_seq + 1,
		    updated_at = NOW()
		RETURNING max_seq
		`
	err := m.conn.QueryRowCtx(ctx, &res, query, convId)
	if err != nil {
		return 0, err
	}
	return res, nil
}
