// app/group/rpc/group.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: group.proto

package group

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Group_CreateGroup_FullMethodName      = "/group.Group/CreateGroup"
	Group_DissolveGroup_FullMethodName    = "/group.Group/DissolveGroup"
	Group_TransferOwner_FullMethodName    = "/group.Group/TransferOwner"
	Group_UpdateGroupInfo_FullMethodName  = "/group.Group/UpdateGroupInfo"
	Group_GetGroupInfo_FullMethodName     = "/group.Group/GetGroupInfo"
	Group_InviteMember_FullMethodName     = "/group.Group/InviteMember"
	Group_ApplyJoinGroup_FullMethodName   = "/group.Group/ApplyJoinGroup"
	Group_HandleApply_FullMethodName      = "/group.Group/HandleApply"
	Group_KickMember_FullMethodName       = "/group.Group/KickMember"
	Group_QuitGroup_FullMethodName        = "/group.Group/QuitGroup"
	Group_MuteMember_FullMethodName       = "/group.Group/MuteMember"
	Group_SetAdmin_FullMethodName         = "/group.Group/SetAdmin"
	Group_GetMembers_FullMethodName       = "/group.Group/GetMembers"
	Group_CheckMember_FullMethodName      = "/group.Group/CheckMember"
	Group_GetMemberVersion_FullMethodName = "/group.Group/GetMemberVersion"
	Group_GetUserGroups_FullMethodName    = "/group.Group/GetUserGroups"
)

// GroupClient is the client API for Group service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 群组服务：群生命周期、成员管理、权限、版本号
type GroupClient interface {
	// ==================== 群生命周期 ====================
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
	DissolveGroup(ctx context.Context, in *DissolveGroupReq, opts ...grpc.CallOption) (*DissolveGroupResp, error)
	TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error)
	UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoReq, opts ...grpc.CallOption) (*UpdateGroupInfoResp, error)
	GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
	// ==================== 成员管理 ====================
	InviteMember(ctx context.Context, in *InviteMemberReq, opts ...grpc.CallOption) (*InviteMemberResp, error)
	ApplyJoinGroup(ctx context.Context, in *ApplyJoinGroupReq, opts ...grpc.CallOption) (*ApplyJoinGroupResp, error)
	HandleApply(ctx context.Context, in *HandleApplyReq, opts ...grpc.CallOption) (*HandleApplyResp, error)
	KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error)
	QuitGroup(ctx context.Context, in *QuitGroupReq, opts ...grpc.CallOption) (*QuitGroupResp, error)
	MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error)
	SetAdmin(ctx context.Context, in *SetAdminReq, opts ...grpc.CallOption) (*SetAdminResp, error)
	// ==================== 查询接口（供 Message 服务调用） ====================
	GetMembers(ctx context.Context, in *GetMembersReq, opts ...grpc.CallOption) (*GetMembersResp, error)
	CheckMember(ctx context.Context, in *CheckMemberReq, opts ...grpc.CallOption) (*CheckMemberResp, error)
	GetMemberVersion(ctx context.Context, in *GetMemberVersionReq, opts ...grpc.CallOption) (*GetMemberVersionResp, error)
	// 用户所在的群 ID 列表(断线重连补拉时组装会话列表用)
	GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error)
}

type groupClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupClient(cc grpc.ClientConnInterface) GroupClient {
	return &groupClient{cc}
}

func (c *groupClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResp)
	err := c.cc.Invoke(ctx, Group_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) DissolveGroup(ctx context.Context, in *DissolveGroupReq, opts ...grpc.CallOption) (*DissolveGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DissolveGroupResp)
	err := c.cc.Invoke(ctx, Group_DissolveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferOwnerResp)
	err := c.cc.Invoke(ctx, Group_TransferOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoReq, opts ...grpc.CallOption) (*UpdateGroupInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupInfoResp)
	err := c.cc.Invoke(ctx, Group_UpdateGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupInfoResp)
	err := c.cc.Invoke(ctx, Group_GetGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) InviteMember(ctx context.Context, in *InviteMemberReq, opts ...grpc.CallOption) (*InviteMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMemberResp)
	err := c.cc.Invoke(ctx, Group_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) ApplyJoinGroup(ctx context.Context, in *ApplyJoinGroupReq, opts ...grpc.CallOption) (*ApplyJoinGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyJoinGroupResp)
	err := c.cc.Invoke(ctx, Group_ApplyJoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) HandleApply(ctx context.Context, in *HandleApplyReq, opts ...grpc.CallOption) (*HandleApplyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleApplyResp)
	err := c.cc.Invoke(ctx, Group_HandleApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickMemberResp)
	err := c.cc.Invoke(ctx, Group_KickMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) QuitGroup(ctx context.Context, in *QuitGroupReq, opts ...grpc.CallOption) (*QuitGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuitGroupResp)
	err := c.cc.Invoke(ctx, Group_QuitGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MuteMemberResp)
	err := c.cc.Invoke(ctx, Group_MuteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) SetAdmin(ctx context.Context, in *SetAdminReq, opts ...grpc.CallOption) (*SetAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAdminResp)
	err := c.cc.Invoke(ctx, Group_SetAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetMembers(ctx context.Context, in *GetMembersReq, opts ...grpc.CallOption) (*GetMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembersResp)
	err := c.cc.Invoke(ctx, Group_GetMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) CheckMember(ctx context.Context, in *CheckMemberReq, opts ...grpc.CallOption) (*CheckMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMemberResp)
	err := c.cc.Invoke(ctx, Group_CheckMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetMemberVersion(ctx context.Context, in *GetMemberVersionReq, opts ...grpc.CallOption) (*GetMemberVersionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberVersionResp)
	err := c.cc.Invoke(ctx, Group_GetMemberVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupsResp)
	err := c.cc.Invoke(ctx, Group_GetUserGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServer is the server API for Group service.
// All implementations must embed UnimplementedGroupServer
// for forward compatibility.
//
// 群组服务：群生命周期、成员管理、权限、版本号
type GroupServer interface {
	// ==================== 群生命周期 ====================
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error)
	DissolveGroup(context.Context, *DissolveGroupReq) (*DissolveGroupResp, error)
	TransferOwner(context.Context, *TransferOwnerReq) (*TransferOwnerResp, error)
	UpdateGroupInfo(context.Context, *UpdateGroupInfoReq) (*UpdateGroupInfoResp, error)
	GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error)
	// ==================== 成员管理 ====================
	InviteMember(context.Context, *InviteMemberReq) (*InviteMemberResp, error)
	ApplyJoinGroup(context.Context, *ApplyJoinGroupReq) (*ApplyJoinGroupResp, error)
	HandleApply(context.Context, *HandleApplyReq) (*HandleApplyResp, error)
	KickMember(context.Context, *KickMemberReq) (*KickMemberResp, error)
	QuitGroup(context.Context, *QuitGroupReq) (*QuitGroupResp, error)
	MuteMember(context.Context, *MuteMemberReq) (*MuteMemberResp, error)
	SetAdmin(context.Context, *SetAdminReq) (*SetAdminResp, error)
	// ==================== 查询接口（供 Message 服务调用） ====================
	GetMembers(context.Context, *GetMembersReq) (*GetMembersResp, error)
	CheckMember(context.Context, *CheckMemberReq) (*CheckMemberResp, error)
	GetMemberVersion(context.Context, *GetMemberVersionReq) (*GetMemberVersionResp, error)
	// 用户所在的群 ID 列表(断线重连补拉时组装会话列表用)
	GetUserGroups(context.Context, *GetUserGroupsReq) (*GetUserGroupsResp, error)
	mustEmbedUnimplementedGroupServer()
}

// UnimplementedGroupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupServer struct{}

func (UnimplementedGroupServer) CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedGroupServer) DissolveGroup(context.Context, *DissolveGroupReq) (*DissolveGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DissolveGroup not implemented")
}
func (UnimplementedGroupServer) TransferOwner(context.Context, *TransferOwnerReq) (*TransferOwnerResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferOwner not implemented")
}
func (UnimplementedGroupServer) UpdateGroupInfo(context.Context, *UpdateGroupInfoReq) (*UpdateGroupInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroupInfo not implemented")
}
func (UnimplementedGroupServer) GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfo not implemented")
}
func (UnimplementedGroupServer) InviteMember(context.Context, *InviteMemberReq) (*InviteMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedGroupServer) ApplyJoinGroup(context.Context, *ApplyJoinGroupReq) (*ApplyJoinGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyJoinGroup not implemented")
}
func (UnimplementedGroupServer) HandleApply(context.Context, *HandleApplyReq) (*HandleApplyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleApply not implemented")
}
func (UnimplementedGroupServer) KickMember(context.Context, *KickMemberReq) (*KickMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method KickMember not implemented")
}
func (UnimplementedGroupServer) QuitGroup(context.Context, *QuitGroupReq) (*QuitGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QuitGroup not implemented")
}
func (UnimplementedGroupServer) MuteMember(context.Context, *MuteMemberReq) (*MuteMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MuteMember not implemented")
}
func (UnimplementedGroupServer) SetAdmin(context.Context, *SetAdminReq) (*SetAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAdmin not implemented")
}
func (UnimplementedGroupServer) GetMembers(context.Context, *GetMembersReq) (*GetMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembers not implemented")
}
func (UnimplementedGroupServer) CheckMember(context.Context, *CheckMemberReq) (*CheckMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckMember not implemented")
}
func (UnimplementedGroupServer) GetMemberVersion(context.Context, *GetMemberVersionReq) (*GetMemberVersionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberVersion not implemented")
}
func (UnimplementedGroupServer) GetUserGroups(context.Context, *GetUserGroupsReq) (*GetUserGroupsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGroups not implemented")
}
func (UnimplementedGroupServer) mustEmbedUnimplementedGroupServer() {}
func (UnimplementedGroupServer) testEmbeddedByValue()               {}

// UnsafeGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupServer will
// result in compilation errors.
type UnsafeGroupServer interface {
	mustEmbedUnimplementedGroupServer()
}

func RegisterGroupServer(s grpc.ServiceRegistrar, srv GroupServer) {
	// If the following call panics, it indicates UnimplementedGroupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Group_ServiceDesc, srv)
}

func _Group_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_DissolveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DissolveGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).DissolveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_DissolveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).DissolveGroup(ctx, req.(*DissolveGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_TransferOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).TransferOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_TransferOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).TransferOwner(ctx, req.(*TransferOwnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_UpdateGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).UpdateGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_UpdateGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).UpdateGroupInfo(ctx, req.(*UpdateGroupInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetGroupInfo(ctx, req.(*GetGroupInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).InviteMember(ctx, req.(*InviteMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_ApplyJoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyJoinGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).ApplyJoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_ApplyJoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).ApplyJoinGroup(ctx, req.(*ApplyJoinGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_HandleApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).HandleApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_HandleApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).HandleApply(ctx, req.(*HandleApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_KickMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).KickMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_KickMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).KickMember(ctx, req.(*KickMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_QuitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).QuitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_QuitGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).QuitGroup(ctx, req.(*QuitGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_MuteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).MuteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_MuteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).MuteMember(ctx, req.(*MuteMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_SetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).SetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_SetAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).SetAdmin(ctx, req.(*SetAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetMembers(ctx, req.(*GetMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_CheckMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).CheckMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_CheckMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).CheckMember(ctx, req.(*CheckMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetMemberVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberVersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetMemberVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetMemberVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetMemberVersion(ctx, req.(*GetMemberVersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetUserGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetUserGroups(ctx, req.(*GetUserGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Group_ServiceDesc is the grpc.ServiceDesc for Group service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Group_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "group.Group",
	HandlerType: (*GroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _Group_CreateGroup_Handler,
		},
		{
			MethodName: "DissolveGroup",
			Handler:    _Group_DissolveGroup_Handler,
		},
		{
			MethodName: "TransferOwner",
			Handler:    _Group_TransferOwner_Handler,
		},
		{
			MethodName: "UpdateGroupInfo",
			Handler:    _Group_UpdateGroupInfo_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _Group_GetGroupInfo_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _Group_InviteMember_Handler,
		},
		{
			MethodName: "ApplyJoinGroup",
			Handler:    _Group_ApplyJoinGroup_Handler,
		},
		{
			MethodName: "HandleApply",
			Handler:    _Group_HandleApply_Handler,
		},
		{
			MethodName: "KickMember",
			Handler:    _Group_KickMember_Handler,
		},
		{
			MethodName: "QuitGroup",
			Handler:    _Group_QuitGroup_Handler,
		},
		{
			MethodName: "MuteMember",
			Handler:    _Group_MuteMember_Handler,
		},
		{
			MethodName: "SetAdmin",
			Handler:    _Group_SetAdmin_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _Group_GetMembers_Handler,
		},
		{
			MethodName: "CheckMember",
			Handler:    _Group_CheckMember_Handler,
		},
		{
			MethodName: "GetMemberVersion",
			Handler:    _Group_GetMemberVersion_Handler,
		},
		{
			MethodName: "GetUserGroups",
			Handler:    _Group_GetUserGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "group.proto",
}
