// app/group/rpc/group.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: group.proto

package group

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupRole int32

const (
	GroupRole_UNKNOWN_ROLE GroupRole = 0
	GroupRole_OWNER        GroupRole = 1 // 群主
	GroupRole_ADMIN        GroupRole = 2 // 管理员
	GroupRole_MEMBER       GroupRole = 3 // 普通成员
)

// Enum value maps for GroupRole.
var (
	GroupRole_name = map[int32]string{
		0: "UNKNOWN_ROLE",
		1: "OWNER",
		2: "ADMIN",
		3: "MEMBER",
	}
	GroupRole_value = map[string]int32{
		"UNKNOWN_ROLE": 0,
		"OWNER":        1,
		"ADMIN":        2,
		"MEMBER":       3,
	}
)

func (x GroupRole) Enum() *GroupRole {
	p := new(GroupRole)
	*p = x
	return p
}

func (x GroupRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupRole) Descriptor() protoreflect.EnumDescriptor {
	return file_group_proto_enumTypes[0].Descriptor()
}

func (GroupRole) Type() protoreflect.EnumType {
	return &file_group_proto_enumTypes[0]
}

func (x GroupRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupRole.Descriptor instead.
func (GroupRole) EnumDescriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{0}
}

type GroupStatus int32

const (
	GroupStatus_UNKNOWN_STATUS GroupStatus = 0
	GroupStatus_NORMAL         GroupStatus = 1 // 正常
	GroupStatus_DISSOLVED      GroupStatus = 2 // 已解散
)

// Enum value maps for GroupStatus.
var (
	GroupStatus_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "NORMAL",
		2: "DISSOLVED",
	}
	GroupStatus_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"NORMAL":         1,
		"DISSOLVED":      2,
	}
)

func (x GroupStatus) Enum() *GroupStatus {
	p := new(GroupStatus)
	*p = x
	return p
}

func (x GroupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_group_proto_enumTypes[1].Descriptor()
}

func (GroupStatus) Type() protoreflect.EnumType {
	return &file_group_proto_enumTypes[1]
}

func (x GroupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupStatus.Descriptor instead.
func (GroupStatus) EnumDescriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{1}
}

type ApplyStatus int32

const (
	ApplyStatus_APPLY_UNKNOWN ApplyStatus = 0
	ApplyStatus_PENDING       ApplyStatus = 1 // 待处理
	ApplyStatus_ACCEPTED      ApplyStatus = 2 // 已接受
	ApplyStatus_REJECTED      ApplyStatus = 3 // 已拒绝
)

// Enum value maps for ApplyStatus.
var (
	ApplyStatus_name = map[int32]string{
		0: "APPLY_UNKNOWN",
		1: "PENDING",
		2: "ACCEPTED",
		3: "REJECTED",
	}
	ApplyStatus_value = map[string]int32{
		"APPLY_UNKNOWN": 0,
		"PENDING":       1,
		"ACCEPTED":      2,
		"REJECTED":      3,
	}
)

func (x ApplyStatus) Enum() *ApplyStatus {
	p := new(ApplyStatus)
	*p = x
	return p
}

func (x ApplyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_group_proto_enumTypes[2].Descriptor()
}

func (ApplyStatus) Type() protoreflect.EnumType {
	return &file_group_proto_enumTypes[2]
}

func (x ApplyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplyStatus.Descriptor instead.
func (ApplyStatus) EnumDescriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{2}
}

type GetUserGroupsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGroupsReq) Reset() {
	*x = GetUserGroupsReq{}
	mi := &file_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGroupsReq) ProtoMessage() {}

func (x *GetUserGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGroupsReq.ProtoReflect.Descriptor instead.
func (*GetUserGroupsReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserGroupsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserGroupsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIds      []int64                `protobuf:"varint,1,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGroupsResp) Reset() {
	*x = GetUserGroupsResp{}
	mi := &file_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGroupsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGroupsResp) ProtoMessage() {}

func (x *GetUserGroupsResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGroupsResp.ProtoReflect.Descriptor instead.
func (*GetUserGroupsResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserGroupsResp) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type GroupInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar           string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	OwnerId          int64                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Notice           string                 `protobuf:"bytes,5,opt,name=notice,proto3" json:"notice,omitempty"`
	MemberCount      int32                  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MaxMember        int32                  `protobuf:"varint,7,opt,name=max_member,json=maxMember,proto3" json:"max_member,omitempty"`
	MemberVersion    int64                  `protobuf:"varint,8,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`           // 成员列表版本号，变更时递增
	GroupType        int32                  `protobuf:"varint,9,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"`                       // 1-普通群 2-企业群
	Status           int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                             // 1-正常 2-解散
	InvitePermission int32                  `protobuf:"varint,11,opt,name=invite_permission,json=invitePermission,proto3" json:"invite_permission,omitempty"` // 1-所有人可邀请 2-仅管理员
	JoinApproval     int32                  `protobuf:"varint,12,opt,name=join_approval,json=joinApproval,proto3" json:"join_approval,omitempty"`             // 1-无需审批 2-需要审批
	CreatedAt        int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{2}
}

func (x *GroupInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupInfo) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GroupInfo) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *GroupInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GroupInfo) GetMaxMember() int32 {
	if x != nil {
		return x.MaxMember
	}
	return 0
}

func (x *GroupInfo) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *GroupInfo) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *GroupInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupInfo) GetInvitePermission() int32 {
	if x != nil {
		return x.InvitePermission
	}
	return 0
}

func (x *GroupInfo) GetJoinApproval() int32 {
	if x != nil {
		return x.JoinApproval
	}
	return 0
}

func (x *GroupInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GroupInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"` // 1-群主 2-管理员 3-普通成员
	GroupNickname string                 `protobuf:"bytes,3,opt,name=group_nickname,json=groupNickname,proto3" json:"group_nickname,omitempty"`
	JoinTime      int64                  `protobuf:"varint,4,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	MuteUntil     int64                  `protobuf:"varint,5,opt,name=mute_until,json=muteUntil,proto3" json:"mute_until,omitempty"` // 禁言截止时间（毫秒时间戳，0 表示未禁言）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{3}
}

func (x *MemberInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *MemberInfo) GetGroupNickname() string {
	if x != nil {
		return x.GroupNickname
	}
	return ""
}

func (x *MemberInfo) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

func (x *MemberInfo) GetMuteUntil() int64 {
	if x != nil {
		return x.MuteUntil
	}
	return 0
}

type CreateGroupReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CreatorId        int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"` // 创建者（自动成为群主）
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar           string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	InitialMembers   []int64                `protobuf:"varint,4,rep,packed,name=initial_members,json=initialMembers,proto3" json:"initial_members,omitempty"` // 初始成员列表（不含创建者）
	MaxMember        int32                  `protobuf:"varint,5,opt,name=max_member,json=maxMember,proto3" json:"max_member,omitempty"`                       // 默认 500
	GroupType        int32                  `protobuf:"varint,6,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"`                       // 1-普通群 2-企业群
	InvitePermission int32                  `protobuf:"varint,7,opt,name=invite_permission,json=invitePermission,proto3" json:"invite_permission,omitempty"`
	JoinApproval     int32                  `protobuf:"varint,8,opt,name=join_approval,json=joinApproval,proto3" json:"join_approval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGroupReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateGroupReq) GetInitialMembers() []int64 {
	if x != nil {
		return x.InitialMembers
	}
	return nil
}

func (x *CreateGroupReq) GetMaxMember() int32 {
	if x != nil {
		return x.MaxMember
	}
	return 0
}

func (x *CreateGroupReq) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *CreateGroupReq) GetInvitePermission() int32 {
	if x != nil {
		return x.InvitePermission
	}
	return 0
}

func (x *CreateGroupReq) GetJoinApproval() int32 {
	if x != nil {
		return x.JoinApproval
	}
	return 0
}

type CreateGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberVersion int64                  `protobuf:"varint,2,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResp) Reset() {
	*x = CreateGroupResp{}
	mi := &file_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResp) ProtoMessage() {}

func (x *CreateGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResp.ProtoReflect.Descriptor instead.
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGroupResp) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

type DissolveGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者（必须是群主）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DissolveGroupReq) Reset() {
	*x = DissolveGroupReq{}
	mi := &file_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DissolveGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissolveGroupReq) ProtoMessage() {}

func (x *DissolveGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissolveGroupReq.ProtoReflect.Descriptor instead.
func (*DissolveGroupReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{6}
}

func (x *DissolveGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DissolveGroupReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type DissolveGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DissolveGroupResp) Reset() {
	*x = DissolveGroupResp{}
	mi := &file_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DissolveGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissolveGroupResp) ProtoMessage() {}

func (x *DissolveGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissolveGroupResp.ProtoReflect.Descriptor instead.
func (*DissolveGroupResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{7}
}

type TransferOwnerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OldOwnerId    int64                  `protobuf:"varint,2,opt,name=old_owner_id,json=oldOwnerId,proto3" json:"old_owner_id,omitempty"`
	NewOwnerId    int64                  `protobuf:"varint,3,opt,name=new_owner_id,json=newOwnerId,proto3" json:"new_owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnerReq) Reset() {
	*x = TransferOwnerReq{}
	mi := &file_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnerReq) ProtoMessage() {}

func (x *TransferOwnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnerReq.ProtoReflect.Descriptor instead.
func (*TransferOwnerReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{8}
}

func (x *TransferOwnerReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *TransferOwnerReq) GetOldOwnerId() int64 {
	if x != nil {
		return x.OldOwnerId
	}
	return 0
}

func (x *TransferOwnerReq) GetNewOwnerId() int64 {
	if x != nil {
		return x.NewOwnerId
	}
	return 0
}

type TransferOwnerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberVersion int64                  `protobuf:"varint,1,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"` // 变更后新版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnerResp) Reset() {
	*x = TransferOwnerResp{}
	mi := &file_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnerResp) ProtoMessage() {}

func (x *TransferOwnerResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnerResp.ProtoReflect.Descriptor instead.
func (*TransferOwnerResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{9}
}

func (x *TransferOwnerResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

type UpdateGroupInfoReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupId          int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId       int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // 空字符串表示不修改
	Avatar           string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Notice           string                 `protobuf:"bytes,5,opt,name=notice,proto3" json:"notice,omitempty"`
	InvitePermission int32                  `protobuf:"varint,6,opt,name=invite_permission,json=invitePermission,proto3" json:"invite_permission,omitempty"`
	JoinApproval     int32                  `protobuf:"varint,7,opt,name=join_approval,json=joinApproval,proto3" json:"join_approval,omitempty"`
	MaxMember        int32                  `protobuf:"varint,8,opt,name=max_member,json=maxMember,proto3" json:"max_member,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateGroupInfoReq) Reset() {
	*x = UpdateGroupInfoReq{}
	mi := &file_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoReq) ProtoMessage() {}

func (x *UpdateGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateGroupInfoReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetInvitePermission() int32 {
	if x != nil {
		return x.InvitePermission
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetJoinApproval() int32 {
	if x != nil {
		return x.JoinApproval
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetMaxMember() int32 {
	if x != nil {
		return x.MaxMember
	}
	return 0
}

type UpdateGroupInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupInfoResp) Reset() {
	*x = UpdateGroupInfoResp{}
	mi := &file_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoResp) ProtoMessage() {}

func (x *UpdateGroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoResp.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{11}
}

type GetGroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoReq) Reset() {
	*x = GetGroupInfoReq{}
	mi := &file_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoReq) ProtoMessage() {}

func (x *GetGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoReq.ProtoReflect.Descriptor instead.
func (*GetGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupInfoReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *GroupInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoResp) Reset() {
	*x = GetGroupInfoResp{}
	mi := &file_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResp) ProtoMessage() {}

func (x *GetGroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResp.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupInfoResp) GetInfo() *GroupInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type InviteMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	InviterId     int64                  `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`  // 邀请人
	UserIds       []int64                `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 被邀请人列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberReq) Reset() {
	*x = InviteMemberReq{}
	mi := &file_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberReq) ProtoMessage() {}

func (x *InviteMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberReq.ProtoReflect.Descriptor instead.
func (*InviteMemberReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{14}
}

func (x *InviteMemberReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *InviteMemberReq) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *InviteMemberReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type InviteMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FailedUserIds []int64                `protobuf:"varint,1,rep,packed,name=failed_user_ids,json=failedUserIds,proto3" json:"failed_user_ids,omitempty"` // 邀请失败的用户（如已达上限）
	MemberVersion int64                  `protobuf:"varint,2,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberResp) Reset() {
	*x = InviteMemberResp{}
	mi := &file_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberResp) ProtoMessage() {}

func (x *InviteMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberResp.ProtoReflect.Descriptor instead.
func (*InviteMemberResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{15}
}

func (x *InviteMemberResp) GetFailedUserIds() []int64 {
	if x != nil {
		return x.FailedUserIds
	}
	return nil
}

func (x *InviteMemberResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

type ApplyJoinGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ApplicantId   int64                  `protobuf:"varint,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	ApplyReason   string                 `protobuf:"bytes,3,opt,name=apply_reason,json=applyReason,proto3" json:"apply_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyJoinGroupReq) Reset() {
	*x = ApplyJoinGroupReq{}
	mi := &file_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyJoinGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyJoinGroupReq) ProtoMessage() {}

func (x *ApplyJoinGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyJoinGroupReq.ProtoReflect.Descriptor instead.
func (*ApplyJoinGroupReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyJoinGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ApplyJoinGroupReq) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *ApplyJoinGroupReq) GetApplyReason() string {
	if x != nil {
		return x.ApplyReason
	}
	return ""
}

type ApplyJoinGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int64                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 1-待处理（需审批） 2-已加入（无需审批）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyJoinGroupResp) Reset() {
	*x = ApplyJoinGroupResp{}
	mi := &file_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyJoinGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyJoinGroupResp) ProtoMessage() {}

func (x *ApplyJoinGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyJoinGroupResp.ProtoReflect.Descriptor instead.
func (*ApplyJoinGroupResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{17}
}

func (x *ApplyJoinGroupResp) GetApplyId() int64 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *ApplyJoinGroupResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type HandleApplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 审批人(群主/管理员)
	ApplyId       int64                  `protobuf:"varint,3,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	Approve       bool                   `protobuf:"varint,4,opt,name=approve,proto3" json:"approve,omitempty"` // true-接受入群 false-拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleApplyReq) Reset() {
	*x = HandleApplyReq{}
	mi := &file_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleApplyReq) ProtoMessage() {}

func (x *HandleApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleApplyReq.ProtoReflect.Descriptor instead.
func (*HandleApplyReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{18}
}

func (x *HandleApplyReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *HandleApplyReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *HandleApplyReq) GetApplyId() int64 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *HandleApplyReq) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type HandleApplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberVersion int64                  `protobuf:"varint,1,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"` // 接受且成功入群时返回新版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleApplyResp) Reset() {
	*x = HandleApplyResp{}
	mi := &file_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleApplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleApplyResp) ProtoMessage() {}

func (x *HandleApplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleApplyResp.ProtoReflect.Descriptor instead.
func (*HandleApplyResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{19}
}

func (x *HandleApplyResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

type KickMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者（群主/管理员）
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`       // 被踢者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMemberReq) Reset() {
	*x = KickMemberReq{}
	mi := &file_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberReq) ProtoMessage() {}

func (x *KickMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberReq.ProtoReflect.Descriptor instead.
func (*KickMemberReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{20}
}

func (x *KickMemberReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *KickMemberReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *KickMemberReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type KickMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberVersion int64                  `protobuf:"varint,1,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMemberResp) Reset() {
	*x = KickMemberResp{}
	mi := &file_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberResp) ProtoMessage() {}

func (x *KickMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberResp.ProtoReflect.Descriptor instead.
func (*KickMemberResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{21}
}

func (x *KickMemberResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

type QuitGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitGroupReq) Reset() {
	*x = QuitGroupReq{}
	mi := &file_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitGroupReq) ProtoMessage() {}

func (x *QuitGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitGroupReq.ProtoReflect.Descriptor instead.
func (*QuitGroupReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{22}
}

func (x *QuitGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *QuitGroupReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type QuitGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberVersion int64                  `protobuf:"varint,1,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitGroupResp) Reset() {
	*x = QuitGroupResp{}
	mi := &file_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitGroupResp) ProtoMessage() {}

func (x *QuitGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitGroupResp.ProtoReflect.Descriptor instead.
func (*QuitGroupResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{23}
}

func (x *QuitGroupResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

type MuteMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MuteUntil     int64                  `protobuf:"varint,4,opt,name=mute_until,json=muteUntil,proto3" json:"mute_until,omitempty"` // 禁言截止时间（毫秒时间戳，0 表示解除禁言）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberReq) Reset() {
	*x = MuteMemberReq{}
	mi := &file_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberReq) ProtoMessage() {}

func (x *MuteMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberReq.ProtoReflect.Descriptor instead.
func (*MuteMemberReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{24}
}

func (x *MuteMemberReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MuteMemberReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *MuteMemberReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *MuteMemberReq) GetMuteUntil() int64 {
	if x != nil {
		return x.MuteUntil
	}
	return 0
}

type MuteMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberResp) Reset() {
	*x = MuteMemberResp{}
	mi := &file_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberResp) ProtoMessage() {}

func (x *MuteMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberResp.ProtoReflect.Descriptor instead.
func (*MuteMemberResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{25}
}

type SetAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 群主
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"` // true-设为管理员 false-降为普通成员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminReq) Reset() {
	*x = SetAdminReq{}
	mi := &file_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminReq) ProtoMessage() {}

func (x *SetAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminReq.ProtoReflect.Descriptor instead.
func (*SetAdminReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{26}
}

func (x *SetAdminReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SetAdminReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *SetAdminReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SetAdminReq) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type SetAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberVersion int64                  `protobuf:"varint,1,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminResp) Reset() {
	*x = SetAdminResp{}
	mi := &file_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminResp) ProtoMessage() {}

func (x *SetAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminResp.ProtoReflect.Descriptor instead.
func (*SetAdminResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{27}
}

func (x *SetAdminResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

type GetMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	LastId        int64                  `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`       // 分页游标（上一页最后一个 user_id，首次传 0）
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 默认 200，最大 200
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersReq) Reset() {
	*x = GetMembersReq{}
	mi := &file_group_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersReq) ProtoMessage() {}

func (x *GetMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersReq.ProtoReflect.Descriptor instead.
func (*GetMembersReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{28}
}

func (x *GetMembersReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetMembersReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *GetMembersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberInfo          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	MemberVersion int64                  `protobuf:"varint,3,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"` // 当前版本号，客户端用于缓存校验
	LastId        int64                  `protobuf:"varint,4,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResp) Reset() {
	*x = GetMembersResp{}
	mi := &file_group_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResp) ProtoMessage() {}

func (x *GetMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResp.ProtoReflect.Descriptor instead.
func (*GetMembersResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{29}
}

func (x *GetMembersResp) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetMembersResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetMembersResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *GetMembersResp) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

type CheckMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberReq) Reset() {
	*x = CheckMemberReq{}
	mi := &file_group_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberReq) ProtoMessage() {}

func (x *CheckMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberReq.ProtoReflect.Descriptor instead.
func (*CheckMemberReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{30}
}

func (x *CheckMemberReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CheckMemberReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`                      // 0-非成员 1-群主 2-管理员 3-普通成员
	IsMuted       bool                   `protobuf:"varint,3,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"` // 当前是否处于禁言状态
	MuteUntil     int64                  `protobuf:"varint,4,opt,name=mute_until,json=muteUntil,proto3" json:"mute_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberResp) Reset() {
	*x = CheckMemberResp{}
	mi := &file_group_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberResp) ProtoMessage() {}

func (x *CheckMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberResp.ProtoReflect.Descriptor instead.
func (*CheckMemberResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{31}
}

func (x *CheckMemberResp) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *CheckMemberResp) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *CheckMemberResp) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *CheckMemberResp) GetMuteUntil() int64 {
	if x != nil {
		return x.MuteUntil
	}
	return 0
}

type GetMemberVersionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberVersionReq) Reset() {
	*x = GetMemberVersionReq{}
	mi := &file_group_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberVersionReq) ProtoMessage() {}

func (x *GetMemberVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberVersionReq.ProtoReflect.Descriptor instead.
func (*GetMemberVersionReq) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{32}
}

func (x *GetMemberVersionReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetMemberVersionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberVersion int64                  `protobuf:"varint,1,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	MemberCount   int32                  `protobuf:"varint,2,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberVersionResp) Reset() {
	*x = GetMemberVersionResp{}
	mi := &file_group_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberVersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberVersionResp) ProtoMessage() {}

func (x *GetMemberVersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberVersionResp.ProtoReflect.Descriptor instead.
func (*GetMemberVersionResp) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{33}
}

func (x *GetMemberVersionResp) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *GetMemberVersionResp) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

var File_group_proto protoreflect.FileDescriptor

const file_group_proto_rawDesc = "" +
	"\n" +
	"\vgroup.proto\x12\x05group\"+\n" +
	"\x10GetUserGroupsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"0\n" +
	"\x11GetUserGroupsResp\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\x03R\bgroupIds\"\xaa\x03\n" +
	"\tGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\x12\x16\n" +
	"\x06notice\x18\x05 \x01(\tR\x06notice\x12!\n" +
	"\fmember_count\x18\x06 \x01(\x05R\vmemberCount\x12\x1d\n" +
	"\n" +
	"max_member\x18\a \x01(\x05R\tmaxMember\x12%\n" +
	"\x0emember_version\x18\b \x01(\x03R\rmemberVersion\x12\x1d\n" +
	"\n" +
	"group_type\x18\t \x01(\x05R\tgroupType\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12+\n" +
	"\x11invite_permission\x18\v \x01(\x05R\x10invitePermission\x12#\n" +
	"\rjoin_approval\x18\f \x01(\x05R\fjoinApproval\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"\x9c\x01\n" +
	"\n" +
	"MemberInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12%\n" +
	"\x0egroup_nickname\x18\x03 \x01(\tR\rgroupNickname\x12\x1b\n" +
	"\tjoin_time\x18\x04 \x01(\x03R\bjoinTime\x12\x1d\n" +
	"\n" +
	"mute_until\x18\x05 \x01(\x03R\tmuteUntil\"\x94\x02\n" +
	"\x0eCreateGroupReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12'\n" +
	"\x0finitial_members\x18\x04 \x03(\x03R\x0einitialMembers\x12\x1d\n" +
	"\n" +
	"max_member\x18\x05 \x01(\x05R\tmaxMember\x12\x1d\n" +
	"\n" +
	"group_type\x18\x06 \x01(\x05R\tgroupType\x12+\n" +
	"\x11invite_permission\x18\a \x01(\x05R\x10invitePermission\x12#\n" +
	"\rjoin_approval\x18\b \x01(\x05R\fjoinApproval\"S\n" +
	"\x0fCreateGroupResp\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12%\n" +
	"\x0emember_version\x18\x02 \x01(\x03R\rmemberVersion\"N\n" +
	"\x10DissolveGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\"\x13\n" +
	"\x11DissolveGroupResp\"q\n" +
	"\x10TransferOwnerReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12 \n" +
	"\fold_owner_id\x18\x02 \x01(\x03R\n" +
	"oldOwnerId\x12 \n" +
	"\fnew_owner_id\x18\x03 \x01(\x03R\n" +
	"newOwnerId\":\n" +
	"\x11TransferOwnerResp\x12%\n" +
	"\x0emember_version\x18\x01 \x01(\x03R\rmemberVersion\"\x85\x02\n" +
	"\x12UpdateGroupInfoReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06notice\x18\x05 \x01(\tR\x06notice\x12+\n" +
	"\x11invite_permission\x18\x06 \x01(\x05R\x10invitePermission\x12#\n" +
	"\rjoin_approval\x18\a \x01(\x05R\fjoinApproval\x12\x1d\n" +
	"\n" +
	"max_member\x18\b \x01(\x05R\tmaxMember\"\x15\n" +
	"\x13UpdateGroupInfoResp\",\n" +
	"\x0fGetGroupInfoReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"8\n" +
	"\x10GetGroupInfoResp\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.group.GroupInfoR\x04info\"f\n" +
	"\x0fInviteMemberReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x02 \x01(\x03R\tinviterId\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\x03R\auserIds\"a\n" +
	"\x10InviteMemberResp\x12&\n" +
	"\x0ffailed_user_ids\x18\x01 \x03(\x03R\rfailedUserIds\x12%\n" +
	"\x0emember_version\x18\x02 \x01(\x03R\rmemberVersion\"t\n" +
	"\x11ApplyJoinGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12!\n" +
	"\fapplicant_id\x18\x02 \x01(\x03R\vapplicantId\x12!\n" +
	"\fapply_reason\x18\x03 \x01(\tR\vapplyReason\"G\n" +
	"\x12ApplyJoinGroupResp\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\x03R\aapplyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\x81\x01\n" +
	"\x0eHandleApplyReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x19\n" +
	"\bapply_id\x18\x03 \x01(\x03R\aapplyId\x12\x18\n" +
	"\aapprove\x18\x04 \x01(\bR\aapprove\"8\n" +
	"\x0fHandleApplyResp\x12%\n" +
	"\x0emember_version\x18\x01 \x01(\x03R\rmemberVersion\"h\n" +
	"\rKickMemberReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"7\n" +
	"\x0eKickMemberResp\x12%\n" +
	"\x0emember_version\x18\x01 \x01(\x03R\rmemberVersion\"B\n" +
	"\fQuitGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"6\n" +
	"\rQuitGroupResp\x12%\n" +
	"\x0emember_version\x18\x01 \x01(\x03R\rmemberVersion\"\x87\x01\n" +
	"\rMuteMemberReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x1d\n" +
	"\n" +
	"mute_until\x18\x04 \x01(\x03R\tmuteUntil\"\x10\n" +
	"\x0eMuteMemberResp\"\x81\x01\n" +
	"\vSetAdminReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\"5\n" +
	"\fSetAdminResp\x12%\n" +
	"\x0emember_version\x18\x01 \x01(\x03R\rmemberVersion\"`\n" +
	"\rGetMembersReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\alast_id\x18\x02 \x01(\x03R\x06lastId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x98\x01\n" +
	"\x0eGetMembersResp\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.group.MemberInfoR\amembers\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12%\n" +
	"\x0emember_version\x18\x03 \x01(\x03R\rmemberVersion\x12\x17\n" +
	"\alast_id\x18\x04 \x01(\x03R\x06lastId\"D\n" +
	"\x0eCheckMemberReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"|\n" +
	"\x0fCheckMemberResp\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12\x19\n" +
	"\bis_muted\x18\x03 \x01(\bR\aisMuted\x12\x1d\n" +
	"\n" +
	"mute_until\x18\x04 \x01(\x03R\tmuteUntil\"0\n" +
	"\x13GetMemberVersionReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"`\n" +
	"\x14GetMemberVersionResp\x12%\n" +
	"\x0emember_version\x18\x01 \x01(\x03R\rmemberVersion\x12!\n" +
	"\fmember_count\x18\x02 \x01(\x05R\vmemberCount*?\n" +
	"\tGroupRole\x12\x10\n" +
	"\fUNKNOWN_ROLE\x10\x00\x12\t\n" +
	"\x05OWNER\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x03*<\n" +
	"\vGroupStatus\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\r\n" +
	"\tDISSOLVED\x10\x02*I\n" +
	"\vApplyStatus\x12\x11\n" +
	"\rAPPLY_UNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bACCEPTED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x032\x8b\b\n" +
	"\x05Group\x12<\n" +
	"\vCreateGroup\x12\x15.group.CreateGroupReq\x1a\x16.group.CreateGroupResp\x12B\n" +
	"\rDissolveGroup\x12\x17.group.DissolveGroupReq\x1a\x18.group.DissolveGroupResp\x12B\n" +
	"\rTransferOwner\x12\x17.group.TransferOwnerReq\x1a\x18.group.TransferOwnerResp\x12H\n" +
	"\x0fUpdateGroupInfo\x12\x19.group.UpdateGroupInfoReq\x1a\x1a.group.UpdateGroupInfoResp\x12?\n" +
	"\fGetGroupInfo\x12\x16.group.GetGroupInfoReq\x1a\x17.group.GetGroupInfoResp\x12?\n" +
	"\fInviteMember\x12\x16.group.InviteMemberReq\x1a\x17.group.InviteMemberResp\x12E\n" +
	"\x0eApplyJoinGroup\x12\x18.group.ApplyJoinGroupReq\x1a\x19.group.ApplyJoinGroupResp\x12<\n" +
	"\vHandleApply\x12\x15.group.HandleApplyReq\x1a\x16.group.HandleApplyResp\x129\n" +
	"\n" +
	"KickMember\x12\x14.group.KickMemberReq\x1a\x15.group.KickMemberResp\x126\n" +
	"\tQuitGroup\x12\x13.group.QuitGroupReq\x1a\x14.group.QuitGroupResp\x129\n" +
	"\n" +
	"MuteMember\x12\x14.group.MuteMemberReq\x1a\x15.group.MuteMemberResp\x123\n" +
	"\bSetAdmin\x12\x12.group.SetAdminReq\x1a\x13.group.SetAdminResp\x129\n" +
	"\n" +
	"GetMembers\x12\x14.group.GetMembersReq\x1a\x15.group.GetMembersResp\x12<\n" +
	"\vCheckMember\x12\x15.group.CheckMemberReq\x1a\x16.group.CheckMemberResp\x12K\n" +
	"\x10GetMemberVersion\x12\x1a.group.GetMemberVersionReq\x1a\x1b.group.GetMemberVersionResp\x12B\n" +
	"\rGetUserGroups\x12\x17.group.GetUserGroupsReq\x1a\x18.group.GetUserGroupsRespB\tZ\a./groupb\x06proto3"

var (
	file_group_proto_rawDescOnce sync.Once
	file_group_proto_rawDescData []byte
)

func file_group_proto_rawDescGZIP() []byte {
	file_group_proto_rawDescOnce.Do(func() {
		file_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)))
	})
	return file_group_proto_rawDescData
}

var file_group_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_group_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_group_proto_goTypes = []any{
	(GroupRole)(0),               // 0: group.GroupRole
	(GroupStatus)(0),             // 1: group.GroupStatus
	(ApplyStatus)(0),             // 2: group.ApplyStatus
	(*GetUserGroupsReq)(nil),     // 3: group.GetUserGroupsReq
	(*GetUserGroupsResp)(nil),    // 4: group.GetUserGroupsResp
	(*GroupInfo)(nil),            // 5: group.GroupInfo
	(*MemberInfo)(nil),           // 6: group.MemberInfo
	(*CreateGroupReq)(nil),       // 7: group.CreateGroupReq
	(*CreateGroupResp)(nil),      // 8: group.CreateGroupResp
	(*DissolveGroupReq)(nil),     // 9: group.DissolveGroupReq
	(*DissolveGroupResp)(nil),    // 10: group.DissolveGroupResp
	(*TransferOwnerReq)(nil),     // 11: group.TransferOwnerReq
	(*TransferOwnerResp)(nil),    // 12: group.TransferOwnerResp
	(*UpdateGroupInfoReq)(nil),   // 13: group.UpdateGroupInfoReq
	(*UpdateGroupInfoResp)(nil),  // 14: group.UpdateGroupInfoResp
	(*GetGroupInfoReq)(nil),      // 15: group.GetGroupInfoReq
	(*GetGroupInfoResp)(nil),     // 16: group.GetGroupInfoResp
	(*InviteMemberReq)(nil),      // 17: group.InviteMemberReq
	(*InviteMemberResp)(nil),     // 18: group.InviteMemberResp
	(*ApplyJoinGroupReq)(nil),    // 19: group.ApplyJoinGroupReq
	(*ApplyJoinGroupResp)(nil),   // 20: group.ApplyJoinGroupResp
	(*HandleApplyReq)(nil),       // 21: group.HandleApplyReq
	(*HandleApplyResp)(nil),      // 22: group.HandleApplyResp
	(*KickMemberReq)(nil),        // 23: group.KickMemberReq
	(*KickMemberResp)(nil),       // 24: group.KickMemberResp
	(*QuitGroupReq)(nil),         // 25: group.QuitGroupReq
	(*QuitGroupResp)(nil),        // 26: group.QuitGroupResp
	(*MuteMemberReq)(nil),        // 27: group.MuteMemberReq
	(*MuteMemberResp)(nil),       // 28: group.MuteMemberResp
	(*SetAdminReq)(nil),          // 29: group.SetAdminReq
	(*SetAdminResp)(nil),         // 30: group.SetAdminResp
	(*GetMembersReq)(nil),        // 31: group.GetMembersReq
	(*GetMembersResp)(nil),       // 32: group.GetMembersResp
	(*CheckMemberReq)(nil),       // 33: group.CheckMemberReq
	(*CheckMemberResp)(nil),      // 34: group.CheckMemberResp
	(*GetMemberVersionReq)(nil),  // 35: group.GetMemberVersionReq
	(*GetMemberVersionResp)(nil), // 36: group.GetMemberVersionResp
}
var file_group_proto_depIdxs = []int32{
	5,  // 0: group.GetGroupInfoResp.info:type_name -> group.GroupInfo
	6,  // 1: group.GetMembersResp.members:type_name -> group.MemberInfo
	7,  // 2: group.Group.CreateGroup:input_type -> group.CreateGroupReq
	9,  // 3: group.Group.DissolveGroup:input_type -> group.DissolveGroupReq
	11, // 4: group.Group.TransferOwner:input_type -> group.TransferOwnerReq
	13, // 5: group.Group.UpdateGroupInfo:input_type -> group.UpdateGroupInfoReq
	15, // 6: group.Group.GetGroupInfo:input_type -> group.GetGroupInfoReq
	17, // 7: group.Group.InviteMember:input_type -> group.InviteMemberReq
	19, // 8: group.Group.ApplyJoinGroup:input_type -> group.ApplyJoinGroupReq
	21, // 9: group.Group.HandleApply:input_type -> group.HandleApplyReq
	23, // 10: group.Group.KickMember:input_type -> group.KickMemberReq
	25, // 11: group.Group.QuitGroup:input_type -> group.QuitGroupReq
	27, // 12: group.Group.MuteMember:input_type -> group.MuteMemberReq
	29, // 13: group.Group.SetAdmin:input_type -> group.SetAdminReq
	31, // 14: group.Group.GetMembers:input_type -> group.GetMembersReq
	33, // 15: group.Group.CheckMember:input_type -> group.CheckMemberReq
	35, // 16: group.Group.GetMemberVersion:input_type -> group.GetMemberVersionReq
	3,  // 17: group.Group.GetUserGroups:input_type -> group.GetUserGroupsReq
	8,  // 18: group.Group.CreateGroup:output_type -> group.CreateGroupResp
	10, // 19: group.Group.DissolveGroup:output_type -> group.DissolveGroupResp
	12, // 20: group.Group.TransferOwner:output_type -> group.TransferOwnerResp
	14, // 21: group.Group.UpdateGroupInfo:output_type -> group.UpdateGroupInfoResp
	16, // 22: group.Group.GetGroupInfo:output_type -> group.GetGroupInfoResp
	18, // 23: group.Group.InviteMember:output_type -> group.InviteMemberResp
	20, // 24: group.Group.ApplyJoinGroup:output_type -> group.ApplyJoinGroupResp
	22, // 25: group.Group.HandleApply:output_type -> group.HandleApplyResp
	24, // 26: group.Group.KickMember:output_type -> group.KickMemberResp
	26, // 27: group.Group.QuitGroup:output_type -> group.QuitGroupResp
	28, // 28: group.Group.MuteMember:output_type -> group.MuteMemberResp
	30, // 29: group.Group.SetAdmin:output_type -> group.SetAdminResp
	32, // 30: group.Group.GetMembers:output_type -> group.GetMembersResp
	34, // 31: group.Group.CheckMember:output_type -> group.CheckMemberResp
	36, // 32: group.Group.GetMemberVersion:output_type -> group.GetMemberVersionResp
	4,  // 33: group.Group.GetUserGroups:output_type -> group.GetUserGroupsResp
	18, // [18:34] is the sub-list for method output_type
	2,  // [2:18] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_group_proto_init() }
func file_group_proto_init() {
	if File_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_group_proto_goTypes,
		DependencyIndexes: file_group_proto_depIdxs,
		EnumInfos:         file_group_proto_enumTypes,
		MessageInfos:      file_group_proto_msgTypes,
	}.Build()
	File_group_proto = out.File
	file_group_proto_goTypes = nil
	file_group_proto_depIdxs = nil
}
