// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"im-platform/app/gateway/rpc/internal/svc"
	"im-platform/common/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	routes := []rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/ws",
			Handler: WsHandler(serverCtx),
		},
	}
	server.AddRoutes(
		rest.WithMiddleware(middleware.AuthMiddleware(serverCtx.TokenManager),
			routes...),
	)
}